package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Epictxnrequests generated by hbm2java
 */
@Entity
@Table(name = "EPICTXNREQUESTS")
public class Epictxnrequests implements java.io.Serializable {

    private String txnsqid;
    private Ipgstatus ipgstatusByStatus;
    private Ipgstatus ipgstatusByRequeststatus;
    private Ipgcountry ipgcountry;
    private Ipgcurrency ipgcurrency;
    private Ipgmerchant ipgmerchant;
    private Ipgbatch ipgbatch;
    private Ipgstatus ipgstatusByResponswstatus;
    private Ipgtransaction ipgtransaction;
    private String txnsessionid;
    private String channelmode;
    private String txncode;
    private String cardtype;
    private String txnname;
    private String mti;
    private String processingcode;
    private String tid;
    private String billtid;
    private String billmid;
    private String cardnumber;
    private String expirdate;
    private String cvv;
    private String fromaccount;
    private String toaccount;
    private String amount;
    private String servicecharge;
    private String paymode;
    private String traceno;
    private String invoiceno;
    private String nii;
    private String billtypecode;
    private String billprovidercode;
    private String billtypename;
    private String billrefno;
    private String loantype;
    private String leasetype;
    private String phonenumber;
    private String nic;
    private String netbalance;
    private String clientip;
    private String chanelip;
    private String hosttype;
    private String settelmentcount;
    private String settelmentamount;
    private String rrn;
    private String authocode;
    private String responsecode;
    private String localdate;
    private String localtime;
    private String localdatetime;
    private String txndate;
    private String txnltime;
    private String txndatetime;
    private String txninitdatetime;
    private String txnreversdatetime;
    private String txnvoiddatetime;
    private String txnbatchuploaddatetime;
    private String txnsettelmentdatetime;
    private String txncompletedatetime;
    private String receiveddatetime;
    private String senttohostdatetime;
    private String receivedfromhostdatetime;
    private String sentdatetime;

    public Epictxnrequests() {
    }

    public Epictxnrequests(String txnsqid) {
        this.txnsqid = txnsqid;
    }

    public Epictxnrequests(String txnsqid, Ipgstatus ipgstatusByStatus, Ipgstatus ipgstatusByRequeststatus, Ipgcountry ipgcountry, Ipgcurrency ipgcurrency, Ipgmerchant ipgmerchant, Ipgbatch ipgbatch, Ipgstatus ipgstatusByResponswstatus, Ipgtransaction ipgtransaction, String txnsessionid, String channelmode, String txncode, String cardtype, String txnname, String mti, String processingcode, String tid, String billtid, String billmid, String cardnumber, String expirdate, String cvv, String fromaccount, String toaccount, String amount, String servicecharge, String paymode, String traceno, String invoiceno, String nii, String billtypecode, String billprovidercode, String billtypename, String billrefno, String loantype, String leasetype, String phonenumber, String nic, String netbalance, String clientip, String chanelip, String hosttype, String settelmentcount, String settelmentamount, String rrn, String authocode, String responsecode, String localdate, String localtime, String localdatetime, String txndate, String txnltime, String txndatetime, String txninitdatetime, String txnreversdatetime, String txnvoiddatetime, String txnbatchuploaddatetime, String txnsettelmentdatetime, String txncompletedatetime, String receiveddatetime, String senttohostdatetime, String receivedfromhostdatetime, String sentdatetime) {
        this.txnsqid = txnsqid;
        this.ipgstatusByStatus = ipgstatusByStatus;
        this.ipgstatusByRequeststatus = ipgstatusByRequeststatus;
        this.ipgcountry = ipgcountry;
        this.ipgcurrency = ipgcurrency;
        this.ipgmerchant = ipgmerchant;
        this.ipgbatch = ipgbatch;
        this.ipgstatusByResponswstatus = ipgstatusByResponswstatus;
        this.ipgtransaction = ipgtransaction;
        this.txnsessionid = txnsessionid;
        this.channelmode = channelmode;
        this.txncode = txncode;
        this.cardtype = cardtype;
        this.txnname = txnname;
        this.mti = mti;
        this.processingcode = processingcode;
        this.tid = tid;
        this.billtid = billtid;
        this.billmid = billmid;
        this.cardnumber = cardnumber;
        this.expirdate = expirdate;
        this.cvv = cvv;
        this.fromaccount = fromaccount;
        this.toaccount = toaccount;
        this.amount = amount;
        this.servicecharge = servicecharge;
        this.paymode = paymode;
        this.traceno = traceno;
        this.invoiceno = invoiceno;
        this.nii = nii;
        this.billtypecode = billtypecode;
        this.billprovidercode = billprovidercode;
        this.billtypename = billtypename;
        this.billrefno = billrefno;
        this.loantype = loantype;
        this.leasetype = leasetype;
        this.phonenumber = phonenumber;
        this.nic = nic;
        this.netbalance = netbalance;
        this.clientip = clientip;
        this.chanelip = chanelip;
        this.hosttype = hosttype;
        this.settelmentcount = settelmentcount;
        this.settelmentamount = settelmentamount;
        this.rrn = rrn;
        this.authocode = authocode;
        this.responsecode = responsecode;
        this.localdate = localdate;
        this.localtime = localtime;
        this.localdatetime = localdatetime;
        this.txndate = txndate;
        this.txnltime = txnltime;
        this.txndatetime = txndatetime;
        this.txninitdatetime = txninitdatetime;
        this.txnreversdatetime = txnreversdatetime;
        this.txnvoiddatetime = txnvoiddatetime;
        this.txnbatchuploaddatetime = txnbatchuploaddatetime;
        this.txnsettelmentdatetime = txnsettelmentdatetime;
        this.txncompletedatetime = txncompletedatetime;
        this.receiveddatetime = receiveddatetime;
        this.senttohostdatetime = senttohostdatetime;
        this.receivedfromhostdatetime = receivedfromhostdatetime;
        this.sentdatetime = sentdatetime;
    }

    @Id
    @Column(name = "TXNSQID", unique = true, nullable = false, length = 14)
    public String getTxnsqid() {
        return this.txnsqid;
    }

    public void setTxnsqid(String txnsqid) {
        this.txnsqid = txnsqid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Ipgstatus getIpgstatusByStatus() {
        return this.ipgstatusByStatus;
    }

    public void setIpgstatusByStatus(Ipgstatus ipgstatusByStatus) {
        this.ipgstatusByStatus = ipgstatusByStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REQUESTSTATUS")
    public Ipgstatus getIpgstatusByRequeststatus() {
        return this.ipgstatusByRequeststatus;
    }

    public void setIpgstatusByRequeststatus(Ipgstatus ipgstatusByRequeststatus) {
        this.ipgstatusByRequeststatus = ipgstatusByRequeststatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRYCODE")
    public Ipgcountry getIpgcountry() {
        return this.ipgcountry;
    }

    public void setIpgcountry(Ipgcountry ipgcountry) {
        this.ipgcountry = ipgcountry;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CURRENCYCODE")
    public Ipgcurrency getIpgcurrency() {
        return this.ipgcurrency;
    }

    public void setIpgcurrency(Ipgcurrency ipgcurrency) {
        this.ipgcurrency = ipgcurrency;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MID")
    public Ipgmerchant getIpgmerchant() {
        return this.ipgmerchant;
    }

    public void setIpgmerchant(Ipgmerchant ipgmerchant) {
        this.ipgmerchant = ipgmerchant;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "MID", referencedColumnName = "MERCHANTID", insertable = false, updatable = false),
        @JoinColumn(name = "BATCHID", referencedColumnName = "BATCHNUMBER", insertable = false, updatable = false)})
    public Ipgbatch getIpgbatch() {
        return this.ipgbatch;
    }

    public void setIpgbatch(Ipgbatch ipgbatch) {
        this.ipgbatch = ipgbatch;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RESPONSWSTATUS")
    public Ipgstatus getIpgstatusByResponswstatus() {
        return this.ipgstatusByResponswstatus;
    }

    public void setIpgstatusByResponswstatus(Ipgstatus ipgstatusByResponswstatus) {
        this.ipgstatusByResponswstatus = ipgstatusByResponswstatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "TXNID", referencedColumnName = "IPGTRANSACTIONID", insertable = false, updatable = false),
        @JoinColumn(name = "MID", referencedColumnName = "MERCHANTID", insertable = false, updatable = false)})
    public Ipgtransaction getIpgtransaction() {
        return this.ipgtransaction;
    }

    public void setIpgtransaction(Ipgtransaction ipgtransaction) {
        this.ipgtransaction = ipgtransaction;
    }

    @Column(name = "TXNSESSIONID", length = 10)
    public String getTxnsessionid() {
        return this.txnsessionid;
    }

    public void setTxnsessionid(String txnsessionid) {
        this.txnsessionid = txnsessionid;
    }

    @Column(name = "CHANNELMODE", length = 4)
    public String getChannelmode() {
        return this.channelmode;
    }

    public void setChannelmode(String channelmode) {
        this.channelmode = channelmode;
    }

    @Column(name = "TXNCODE", length = 2)
    public String getTxncode() {
        return this.txncode;
    }

    public void setTxncode(String txncode) {
        this.txncode = txncode;
    }

    @Column(name = "CARDTYPE", length = 2)
    public String getCardtype() {
        return this.cardtype;
    }

    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    @Column(name = "TXNNAME", length = 50)
    public String getTxnname() {
        return this.txnname;
    }

    public void setTxnname(String txnname) {
        this.txnname = txnname;
    }

    @Column(name = "MTI", length = 4)
    public String getMti() {
        return this.mti;
    }

    public void setMti(String mti) {
        this.mti = mti;
    }

    @Column(name = "PROCESSINGCODE", length = 6)
    public String getProcessingcode() {
        return this.processingcode;
    }

    public void setProcessingcode(String processingcode) {
        this.processingcode = processingcode;
    }

    @Column(name = "TID", length = 8)
    public String getTid() {
        return this.tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    @Column(name = "BILLTID", length = 8)
    public String getBilltid() {
        return this.billtid;
    }

    public void setBilltid(String billtid) {
        this.billtid = billtid;
    }

    @Column(name = "BILLMID", length = 15)
    public String getBillmid() {
        return this.billmid;
    }

    public void setBillmid(String billmid) {
        this.billmid = billmid;
    }

    @Column(name = "CARDNUMBER", length = 20)
    public String getCardnumber() {
        return this.cardnumber;
    }

    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }

    @Column(name = "EXPIRDATE", length = 4)
    public String getExpirdate() {
        return this.expirdate;
    }

    public void setExpirdate(String expirdate) {
        this.expirdate = expirdate;
    }

    @Column(name = "CVV", length = 4)
    public String getCvv() {
        return this.cvv;
    }

    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    @Column(name = "FROMACCOUNT", length = 20)
    public String getFromaccount() {
        return this.fromaccount;
    }

    public void setFromaccount(String fromaccount) {
        this.fromaccount = fromaccount;
    }

    @Column(name = "TOACCOUNT", length = 20)
    public String getToaccount() {
        return this.toaccount;
    }

    public void setToaccount(String toaccount) {
        this.toaccount = toaccount;
    }

    @Column(name = "AMOUNT", length = 12)
    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    @Column(name = "SERVICECHARGE", length = 12)
    public String getServicecharge() {
        return this.servicecharge;
    }

    public void setServicecharge(String servicecharge) {
        this.servicecharge = servicecharge;
    }

    @Column(name = "PAYMODE", length = 12)
    public String getPaymode() {
        return this.paymode;
    }

    public void setPaymode(String paymode) {
        this.paymode = paymode;
    }

    @Column(name = "TRACENO", length = 6)
    public String getTraceno() {
        return this.traceno;
    }

    public void setTraceno(String traceno) {
        this.traceno = traceno;
    }

    @Column(name = "INVOICENO", length = 6)
    public String getInvoiceno() {
        return this.invoiceno;
    }

    public void setInvoiceno(String invoiceno) {
        this.invoiceno = invoiceno;
    }

    @Column(name = "NII", length = 4)
    public String getNii() {
        return this.nii;
    }

    public void setNii(String nii) {
        this.nii = nii;
    }

    @Column(name = "BILLTYPECODE", length = 2)
    public String getBilltypecode() {
        return this.billtypecode;
    }

    public void setBilltypecode(String billtypecode) {
        this.billtypecode = billtypecode;
    }

    @Column(name = "BILLPROVIDERCODE", length = 2)
    public String getBillprovidercode() {
        return this.billprovidercode;
    }

    public void setBillprovidercode(String billprovidercode) {
        this.billprovidercode = billprovidercode;
    }

    @Column(name = "BILLTYPENAME", length = 30)
    public String getBilltypename() {
        return this.billtypename;
    }

    public void setBilltypename(String billtypename) {
        this.billtypename = billtypename;
    }

    @Column(name = "BILLREFNO", length = 20)
    public String getBillrefno() {
        return this.billrefno;
    }

    public void setBillrefno(String billrefno) {
        this.billrefno = billrefno;
    }

    @Column(name = "LOANTYPE", length = 30)
    public String getLoantype() {
        return this.loantype;
    }

    public void setLoantype(String loantype) {
        this.loantype = loantype;
    }

    @Column(name = "LEASETYPE", length = 30)
    public String getLeasetype() {
        return this.leasetype;
    }

    public void setLeasetype(String leasetype) {
        this.leasetype = leasetype;
    }

    @Column(name = "PHONENUMBER", length = 25)
    public String getPhonenumber() {
        return this.phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    @Column(name = "NIC", length = 20)
    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    @Column(name = "NETBALANCE", length = 20)
    public String getNetbalance() {
        return this.netbalance;
    }

    public void setNetbalance(String netbalance) {
        this.netbalance = netbalance;
    }

    @Column(name = "CLIENTIP", length = 20)
    public String getClientip() {
        return this.clientip;
    }

    public void setClientip(String clientip) {
        this.clientip = clientip;
    }

    @Column(name = "CHANELIP", length = 20)
    public String getChanelip() {
        return this.chanelip;
    }

    public void setChanelip(String chanelip) {
        this.chanelip = chanelip;
    }

    @Column(name = "HOSTTYPE", length = 5)
    public String getHosttype() {
        return this.hosttype;
    }

    public void setHosttype(String hosttype) {
        this.hosttype = hosttype;
    }

    @Column(name = "SETTELMENTCOUNT", length = 20)
    public String getSettelmentcount() {
        return this.settelmentcount;
    }

    public void setSettelmentcount(String settelmentcount) {
        this.settelmentcount = settelmentcount;
    }

    @Column(name = "SETTELMENTAMOUNT", length = 20)
    public String getSettelmentamount() {
        return this.settelmentamount;
    }

    public void setSettelmentamount(String settelmentamount) {
        this.settelmentamount = settelmentamount;
    }

    @Column(name = "RRN", length = 12)
    public String getRrn() {
        return this.rrn;
    }

    public void setRrn(String rrn) {
        this.rrn = rrn;
    }

    @Column(name = "AUTHOCODE", length = 6)
    public String getAuthocode() {
        return this.authocode;
    }

    public void setAuthocode(String authocode) {
        this.authocode = authocode;
    }

    @Column(name = "RESPONSECODE", length = 4)
    public String getResponsecode() {
        return this.responsecode;
    }

    public void setResponsecode(String responsecode) {
        this.responsecode = responsecode;
    }

    @Column(name = "LOCALDATE", length = 4)
    public String getLocaldate() {
        return this.localdate;
    }

    public void setLocaldate(String localdate) {
        this.localdate = localdate;
    }

    @Column(name = "LOCALTIME", length = 6)
    public String getLocaltime() {
        return this.localtime;
    }

    public void setLocaltime(String localtime) {
        this.localtime = localtime;
    }

    @Column(name = "LOCALDATETIME", length = 12)
    public String getLocaldatetime() {
        return this.localdatetime;
    }

    public void setLocaldatetime(String localdatetime) {
        this.localdatetime = localdatetime;
    }

    @Column(name = "TXNDATE", length = 4)
    public String getTxndate() {
        return this.txndate;
    }

    public void setTxndate(String txndate) {
        this.txndate = txndate;
    }

    @Column(name = "TXNLTIME", length = 6)
    public String getTxnltime() {
        return this.txnltime;
    }

    public void setTxnltime(String txnltime) {
        this.txnltime = txnltime;
    }

    @Column(name = "TXNDATETIME", length = 10)
    public String getTxndatetime() {
        return this.txndatetime;
    }

    public void setTxndatetime(String txndatetime) {
        this.txndatetime = txndatetime;
    }

    @Column(name = "TXNINITDATETIME", length = 20)
    public String getTxninitdatetime() {
        return this.txninitdatetime;
    }

    public void setTxninitdatetime(String txninitdatetime) {
        this.txninitdatetime = txninitdatetime;
    }

    @Column(name = "TXNREVERSDATETIME", length = 20)
    public String getTxnreversdatetime() {
        return this.txnreversdatetime;
    }

    public void setTxnreversdatetime(String txnreversdatetime) {
        this.txnreversdatetime = txnreversdatetime;
    }

    @Column(name = "TXNVOIDDATETIME", length = 20)
    public String getTxnvoiddatetime() {
        return this.txnvoiddatetime;
    }

    public void setTxnvoiddatetime(String txnvoiddatetime) {
        this.txnvoiddatetime = txnvoiddatetime;
    }

    @Column(name = "TXNBATCHUPLOADDATETIME", length = 20)
    public String getTxnbatchuploaddatetime() {
        return this.txnbatchuploaddatetime;
    }

    public void setTxnbatchuploaddatetime(String txnbatchuploaddatetime) {
        this.txnbatchuploaddatetime = txnbatchuploaddatetime;
    }

    @Column(name = "TXNSETTELMENTDATETIME", length = 20)
    public String getTxnsettelmentdatetime() {
        return this.txnsettelmentdatetime;
    }

    public void setTxnsettelmentdatetime(String txnsettelmentdatetime) {
        this.txnsettelmentdatetime = txnsettelmentdatetime;
    }

    @Column(name = "TXNCOMPLETEDATETIME", length = 20)
    public String getTxncompletedatetime() {
        return this.txncompletedatetime;
    }

    public void setTxncompletedatetime(String txncompletedatetime) {
        this.txncompletedatetime = txncompletedatetime;
    }

    @Column(name = "RECEIVEDDATETIME", length = 30)
    public String getReceiveddatetime() {
        return this.receiveddatetime;
    }

    public void setReceiveddatetime(String receiveddatetime) {
        this.receiveddatetime = receiveddatetime;
    }

    @Column(name = "SENTTOHOSTDATETIME", length = 30)
    public String getSenttohostdatetime() {
        return this.senttohostdatetime;
    }

    public void setSenttohostdatetime(String senttohostdatetime) {
        this.senttohostdatetime = senttohostdatetime;
    }

    @Column(name = "RECEIVEDFROMHOSTDATETIME", length = 30)
    public String getReceivedfromhostdatetime() {
        return this.receivedfromhostdatetime;
    }

    public void setReceivedfromhostdatetime(String receivedfromhostdatetime) {
        this.receivedfromhostdatetime = receivedfromhostdatetime;
    }

    @Column(name = "SENTDATETIME", length = 30)
    public String getSentdatetime() {
        return this.sentdatetime;
    }

    public void setSentdatetime(String sentdatetime) {
        this.sentdatetime = sentdatetime;
    }
}
