package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Epictxnreversdetails generated by hbm2java
 */
@Entity
@Table(name="EPICTXNREVERSDETAILS")
public class Epictxnreversdetails  implements java.io.Serializable {


     private EpictxnreversdetailsId id;

    public Epictxnreversdetails() {
    }

    public Epictxnreversdetails(EpictxnreversdetailsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="mti", column=@Column(name="MTI", length=4) ), 
        @AttributeOverride(name="processingcode", column=@Column(name="PROCESSINGCODE", length=6) ), 
        @AttributeOverride(name="txndate", column=@Column(name="TXNDATE", length=4) ), 
        @AttributeOverride(name="txntime", column=@Column(name="TXNTIME", length=6) ), 
        @AttributeOverride(name="traceno", column=@Column(name="TRACENO", length=6) ), 
        @AttributeOverride(name="rrn", column=@Column(name="RRN", length=12) ), 
        @AttributeOverride(name="authocode", column=@Column(name="AUTHOCODE", length=6) ), 
        @AttributeOverride(name="tid", column=@Column(name="TID", length=8) ), 
        @AttributeOverride(name="mid", column=@Column(name="MID", length=15) ), 
        @AttributeOverride(name="amount", column=@Column(name="AMOUNT", length=12) ) } )
    public EpictxnreversdetailsId getId() {
        return this.id;
    }
    
    public void setId(EpictxnreversdetailsId id) {
        this.id = id;
    }




}


