package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipg3dsecureverificationrequest generated by hbm2java
 */
@Entity
@Table(name="IPG3DSECUREVERIFICATIONREQUEST")
public class Ipg3dsecureverificationrequest  implements java.io.Serializable {


     private String ipgtransactionid;
     private String cardholderpan;
     private String acquirerbin;
     private String merchantid;
     private String merchantname;
     private String countrycode;
     private BigDecimal merchanttransactionid;
     private String purchasedatetime;
     private Integer amount;
     private String currency;
     private String exponent;
     private String password;
     private String cardexpirydate;
     private String devicecategory;
     private String acceptheader;
     private String useragent;
     private String messageextention;
     private String orderdescription;
     private String field1;
     private String field2;
     private String field3;
     private String field4;
     private String field5;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipg3dsecureverificationrequest() {
    }

	
    public Ipg3dsecureverificationrequest(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }
    public Ipg3dsecureverificationrequest(String ipgtransactionid, String cardholderpan, String acquirerbin, String merchantid, String merchantname, String countrycode, BigDecimal merchanttransactionid, String purchasedatetime, Integer amount, String currency, String exponent, String password, String cardexpirydate, String devicecategory, String acceptheader, String useragent, String messageextention, String orderdescription, String field1, String field2, String field3, String field4, String field5, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.ipgtransactionid = ipgtransactionid;
       this.cardholderpan = cardholderpan;
       this.acquirerbin = acquirerbin;
       this.merchantid = merchantid;
       this.merchantname = merchantname;
       this.countrycode = countrycode;
       this.merchanttransactionid = merchanttransactionid;
       this.purchasedatetime = purchasedatetime;
       this.amount = amount;
       this.currency = currency;
       this.exponent = exponent;
       this.password = password;
       this.cardexpirydate = cardexpirydate;
       this.devicecategory = devicecategory;
       this.acceptheader = acceptheader;
       this.useragent = useragent;
       this.messageextention = messageextention;
       this.orderdescription = orderdescription;
       this.field1 = field1;
       this.field2 = field2;
       this.field3 = field3;
       this.field4 = field4;
       this.field5 = field5;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 
    
    @Column(name="IPGTRANSACTIONID", unique=true, nullable=false, length=20)
    public String getIpgtransactionid() {
        return this.ipgtransactionid;
    }
    
    public void setIpgtransactionid(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }
    
    @Column(name="CARDHOLDERPAN")
    public String getCardholderpan() {
        return this.cardholderpan;
    }
    
    public void setCardholderpan(String cardholderpan) {
        this.cardholderpan = cardholderpan;
    }
    
    @Column(name="ACQUIRERBIN")
    public String getAcquirerbin() {
        return this.acquirerbin;
    }
    
    public void setAcquirerbin(String acquirerbin) {
        this.acquirerbin = acquirerbin;
    }
    
    @Column(name="MERCHANTID", length=15)
    public String getMerchantid() {
        return this.merchantid;
    }
    
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }
    
    @Column(name="MERCHANTNAME")
    public String getMerchantname() {
        return this.merchantname;
    }
    
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname;
    }
    
    @Column(name="COUNTRYCODE", length=16)
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    
    @Column(name="MERCHANTTRANSACTIONID", precision=22, scale=0)
    public BigDecimal getMerchanttransactionid() {
        return this.merchanttransactionid;
    }
    
    public void setMerchanttransactionid(BigDecimal merchanttransactionid) {
        this.merchanttransactionid = merchanttransactionid;
    }
    
    @Column(name="PURCHASEDATETIME", length=64)
    public String getPurchasedatetime() {
        return this.purchasedatetime;
    }
    
    public void setPurchasedatetime(String purchasedatetime) {
        this.purchasedatetime = purchasedatetime;
    }
    
    @Column(name="AMOUNT", precision=9, scale=0)
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    
    @Column(name="CURRENCY", length=64)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="EXPONENT", length=64)
    public String getExponent() {
        return this.exponent;
    }
    
    public void setExponent(String exponent) {
        this.exponent = exponent;
    }
    
    @Column(name="PASSWORD")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="CARDEXPIRYDATE", length=4)
    public String getCardexpirydate() {
        return this.cardexpirydate;
    }
    
    public void setCardexpirydate(String cardexpirydate) {
        this.cardexpirydate = cardexpirydate;
    }
    
    @Column(name="DEVICECATEGORY")
    public String getDevicecategory() {
        return this.devicecategory;
    }
    
    public void setDevicecategory(String devicecategory) {
        this.devicecategory = devicecategory;
    }
    
    @Column(name="ACCEPTHEADER")
    public String getAcceptheader() {
        return this.acceptheader;
    }
    
    public void setAcceptheader(String acceptheader) {
        this.acceptheader = acceptheader;
    }
    
    @Column(name="USERAGENT")
    public String getUseragent() {
        return this.useragent;
    }
    
    public void setUseragent(String useragent) {
        this.useragent = useragent;
    }
    
    @Column(name="MESSAGEEXTENTION")
    public String getMessageextention() {
        return this.messageextention;
    }
    
    public void setMessageextention(String messageextention) {
        this.messageextention = messageextention;
    }
    
    @Column(name="ORDERDESCRIPTION")
    public String getOrderdescription() {
        return this.orderdescription;
    }
    
    public void setOrderdescription(String orderdescription) {
        this.orderdescription = orderdescription;
    }
    
    @Column(name="FIELD1")
    public String getField1() {
        return this.field1;
    }
    
    public void setField1(String field1) {
        this.field1 = field1;
    }
    
    @Column(name="FIELD2")
    public String getField2() {
        return this.field2;
    }
    
    public void setField2(String field2) {
        this.field2 = field2;
    }
    
    @Column(name="FIELD3")
    public String getField3() {
        return this.field3;
    }
    
    public void setField3(String field3) {
        this.field3 = field3;
    }
    
    @Column(name="FIELD4")
    public String getField4() {
        return this.field4;
    }
    
    public void setField4(String field4) {
        this.field4 = field4;
    }
    
    @Column(name="FIELD5")
    public String getField5() {
        return this.field5;
    }
    
    public void setField5(String field5) {
        this.field5 = field5;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


