package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipg3dsecureverificationres generated by hbm2java
 */
@Entity
@Table(name="IPG3DSECUREVERIFICATIONRES")
public class Ipg3dsecureverificationres  implements java.io.Serializable {


     private String ipgtransactionid;
     private String accountholderauthenticationval;
     private String ecivalue;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipg3dsecureverificationres() {
    }

	
    public Ipg3dsecureverificationres(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }
    public Ipg3dsecureverificationres(String ipgtransactionid, String accountholderauthenticationval, String ecivalue, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.ipgtransactionid = ipgtransactionid;
       this.accountholderauthenticationval = accountholderauthenticationval;
       this.ecivalue = ecivalue;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 
    
    @Column(name="IPGTRANSACTIONID", unique=true, nullable=false, length=20)
    public String getIpgtransactionid() {
        return this.ipgtransactionid;
    }
    
    public void setIpgtransactionid(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }
    
    @Column(name="ACCOUNTHOLDERAUTHENTICATIONVAL")
    public String getAccountholderauthenticationval() {
        return this.accountholderauthenticationval;
    }
    
    public void setAccountholderauthenticationval(String accountholderauthenticationval) {
        this.accountholderauthenticationval = accountholderauthenticationval;
    }
    
    @Column(name="ECIVALUE")
    public String getEcivalue() {
        return this.ecivalue;
    }
    
    public void setEcivalue(String ecivalue) {
        this.ecivalue = ecivalue;
    }
    
    @Column(name="LASTUPDATEDUSER")
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


