package com.epic.epay.ipg.util.mapping;
// Generated 02/10/2014 7:08:43 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ipgauthconfiguration generated by hbm2java
 */
@Entity
@Table(name="IPGAUTHCONFIGURATION")
public class Ipgauthconfiguration  implements java.io.Serializable {


     private IpgauthconfigurationId id;
     private String status;

    public Ipgauthconfiguration() {
    }

	
    public Ipgauthconfiguration(IpgauthconfigurationId id) {
        this.id = id;
    }
    public Ipgauthconfiguration(IpgauthconfigurationId id, String status) {
       this.id = id;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cardassociationcode", column=@Column(name="CARDASSOCIATIONCODE", nullable=false, length=20) ), 
        @AttributeOverride(name="ecivalue", column=@Column(name="ECIVALUE", nullable=false, length=20) ), 
        @AttributeOverride(name="txstatus", column=@Column(name="TXSTATUS", nullable=false, length=20) ) } )
    public IpgauthconfigurationId getId() {
        return this.id;
    }
    
    public void setId(IpgauthconfigurationId id) {
        this.id = id;
    }

    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


