package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgaddress generated by hbm2java
 */
@Entity
@Table(name = "IPGADDRESS")
public class Ipgaddress implements java.io.Serializable {

    private long addressid;
    private String address1;
    private String address2;
    private String city;
    private String statecode;
    private String postalcode;
    private String province;
    private String countrycode;
    private String mobile;
    private String telno;
    private String fax;
    private String email;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgmerchant> ipgmerchants = new HashSet<Ipgmerchant>(0);
    private Set<Ipgheadmerchant> ipgheadmerchants = new HashSet<Ipgheadmerchant>(0);

    public Ipgaddress() {
    }

    public Ipgaddress(long addressid) {
        this.addressid = addressid;
    }

    public Ipgaddress(long addressid, String address1, String address2, String city, String statecode, String postalcode, String province, String countrycode, String mobile, String telno, String fax, String email, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgmerchant> ipgmerchants, Set<Ipgheadmerchant> ipgheadmerchants) {
        this.addressid = addressid;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.statecode = statecode;
        this.postalcode = postalcode;
        this.province = province;
        this.countrycode = countrycode;
        this.mobile = mobile;
        this.telno = telno;
        this.fax = fax;
        this.email = email;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgmerchants = ipgmerchants;
        this.ipgheadmerchants = ipgheadmerchants;
    }


    @Id
    @javax.persistence.SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGADDRESSID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name = "ADDRESSID", unique = true, nullable = false, precision = 16, scale = 0)

    public long getAddressid() {
        return this.addressid;
    }

    
    public void setAddressid(long addressid) {
        this.addressid = addressid;
    }

    @Column(name = "ADDRESS1")
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "ADDRESS2")
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "CITY", length = 64)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "STATECODE", length = 16)
    public String getStatecode() {
        return this.statecode;
    }

    public void setStatecode(String statecode) {
        this.statecode = statecode;
    }

    @Column(name = "POSTALCODE", length = 64)
    public String getPostalcode() {
        return this.postalcode;
    }

    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    @Column(name = "PROVINCE", length = 64)
    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    @Column(name = "COUNTRYCODE", length = 16)
    public String getCountrycode() {
        return this.countrycode;
    }

    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    @Column(name = "MOBILE", length = 64)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "TELNO", length = 16)
    public String getTelno() {
        return this.telno;
    }

    public void setTelno(String telno) {
        this.telno = telno;
    }

    @Column(name = "FAX", length = 16)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "EMAIL")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgaddress")
    public Set<Ipgmerchant> getIpgmerchants() {
        return this.ipgmerchants;
    }

    public void setIpgmerchants(Set<Ipgmerchant> ipgmerchants) {
        this.ipgmerchants = ipgmerchants;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgaddress")
    public Set<Ipgheadmerchant> getIpgheadmerchants() {
        return this.ipgheadmerchants;
    }

    public void setIpgheadmerchants(Set<Ipgheadmerchant> ipgheadmerchants) {
        this.ipgheadmerchants = ipgheadmerchants;
    }
}
