package com.epic.epay.ipg.util.mapping;
// Generated 02/10/2014 7:08:43 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgauthconfigurationId generated by hbm2java
 */
@Embeddable
public class IpgauthconfigurationId  implements java.io.Serializable {


     private String cardassociationcode;
     private String ecivalue;
     private String txstatus;

    public IpgauthconfigurationId() {
    }

    public IpgauthconfigurationId(String cardassociationcode, String ecivalue, String txstatus) {
       this.cardassociationcode = cardassociationcode;
       this.ecivalue = ecivalue;
       this.txstatus = txstatus;
    }
   


    @Column(name="CARDASSOCIATIONCODE", nullable=false, length=20)
    public String getCardassociationcode() {
        return this.cardassociationcode;
    }
    
    public void setCardassociationcode(String cardassociationcode) {
        this.cardassociationcode = cardassociationcode;
    }


    @Column(name="ECIVALUE", nullable=false, length=20)
    public String getEcivalue() {
        return this.ecivalue;
    }
    
    public void setEcivalue(String ecivalue) {
        this.ecivalue = ecivalue;
    }


    @Column(name="TXSTATUS", nullable=false, length=20)
    public String getTxstatus() {
        return this.txstatus;
    }
    
    public void setTxstatus(String txstatus) {
        this.txstatus = txstatus;
    }




}


