package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ipgcommonfilepath generated by hbm2java
 */
@Entity
@Table(name = "IPGCOMMONFILEPATH")
public class Ipgcommonfilepath implements java.io.Serializable {

    private String ostype;
    private String transactionlog;
    private String infolog;
    private String errorlog;
    private String certificates;
    private String ccbtxnfiles;
    private String dsenrollrpt;
    private String addonlogopath;
    private String keystorepath;
    private String certpath;
    private String keypath;
    private String ipgmerchanlogin;
    private String ipgrulevalidation;
    private String mpiresponse;
    private String mpirequest;
    private String switchrequest;
    private String switchresponse;
    private String adminerrorlog;
    private String settlementfilepath;

    public Ipgcommonfilepath() {
    }

    public Ipgcommonfilepath(String ostype) {
        this.ostype = ostype;
    }

    public Ipgcommonfilepath(String ostype, String transactionlog, String infolog, String errorlog, String certificates,
            String ccbtxnfiles, String dsenrollrpt, String addonlogopath, String keystorepath, String certpath, String keypath,
            String ipgmerchanlogin, String ipgrulevalidation, String mpiresponse, String mpirequest, String switchrequest, String switchresponse, String adminerrorlog, String settlementfilepath) {
        this.ostype = ostype;
        this.transactionlog = transactionlog;
        this.infolog = infolog;
        this.errorlog = errorlog;
        this.certificates = certificates;
        this.ccbtxnfiles = ccbtxnfiles;
        this.dsenrollrpt = dsenrollrpt;
        this.addonlogopath = addonlogopath;
        this.keystorepath = keystorepath;
        this.certpath = certpath;
        this.keypath = keypath;
        this.ipgmerchanlogin = ipgmerchanlogin;
        this.ipgrulevalidation = ipgrulevalidation;
        this.mpiresponse = mpiresponse;
        this.mpirequest = mpirequest;
        this.switchrequest = switchrequest;
        this.switchresponse = switchresponse;
        this.adminerrorlog = adminerrorlog;
        this.settlementfilepath = settlementfilepath;

    }

    @Id
    @Column(name = "OSTYPE", unique = true, nullable = false, length = 8)
    public String getOstype() {
        return this.ostype;
    }

    public void setOstype(String ostype) {
        this.ostype = ostype;
    }

    @Column(name = "TRANSACTIONLOG", length = 128)
    public String getTransactionlog() {
        return this.transactionlog;
    }

    public void setTransactionlog(String transactionlog) {
        this.transactionlog = transactionlog;
    }

    @Column(name = "INFOLOG", length = 128)
    public String getInfolog() {
        return this.infolog;
    }

    public void setInfolog(String infolog) {
        this.infolog = infolog;
    }

    @Column(name = "ERRORLOG", length = 128)
    public String getErrorlog() {
        return this.errorlog;
    }

    public void setErrorlog(String errorlog) {
        this.errorlog = errorlog;
    }

    @Column(name = "CERTIFICATES", length = 128)
    public String getCertificates() {
        return this.certificates;
    }

    public void setCertificates(String certificates) {
        this.certificates = certificates;
    }

    @Column(name = "CCBTXNFILES", length = 32)
    public String getCcbtxnfiles() {
        return this.ccbtxnfiles;
    }

    public void setCcbtxnfiles(String ccbtxnfiles) {
        this.ccbtxnfiles = ccbtxnfiles;
    }

    @Column(name = "DSENROLLRPT", length = 128)
    public String getDsenrollrpt() {
        return this.dsenrollrpt;
    }

    public void setDsenrollrpt(String dsenrollrpt) {
        this.dsenrollrpt = dsenrollrpt;
    }

    @Column(name = "ADDONLOGOPATH", length = 128)
    public String getAddonlogopath() {
        return addonlogopath;
    }

    public void setAddonlogopath(String addonlogopath) {
        this.addonlogopath = addonlogopath;
    }

    @Column(name = "KEYSTOREPATH", length = 128)
    public String getKeystorepath() {
        return this.keystorepath;
    }

    public void setKeystorepath(String keystorepath) {
        this.keystorepath = keystorepath;
    }

    @Column(name = "CERTPATH", length = 128)
    public String getCertpath() {
        return this.certpath;
    }

    public void setCertpath(String certpath) {
        this.certpath = certpath;
    }

    @Column(name = "KEYPATH", length = 128)
    public String getKeypath() {
        return this.keypath;
    }

    public void setKeypath(String keypath) {
        this.keypath = keypath;
    }

    @Column(name = "IPGMERCHANLOGIN", length = 128)
    public String getIpgmerchanlogin() {
        return ipgmerchanlogin;
    }

    public void setIpgmerchanlogin(String ipgmerchanlogin) {
        this.ipgmerchanlogin = ipgmerchanlogin;
    }

    @Column(name = "IPGRULEVALIDATION", length = 128)
    public String getIpgrulevalidation() {
        return ipgrulevalidation;
    }

    public void setIpgrulevalidation(String ipgrulevalidation) {
        this.ipgrulevalidation = ipgrulevalidation;
    }

    @Column(name = "MPIRESPONSE", length = 128)
    public String getMpiresponse() {
        return mpiresponse;
    }

    public void setMpiresponse(String mpiresponse) {
        this.mpiresponse = mpiresponse;
    }

    @Column(name = "MPIREQUEST", length = 128)
    public String getMpirequest() {
        return mpirequest;
    }

    public void setMpirequest(String mpirequest) {
        this.mpirequest = mpirequest;
    }

    @Column(name = "SWITCHREQUEST", length = 128)
    public String getSwitchrequest() {
        return switchrequest;
    }

    public void setSwitchrequest(String switchrequest) {
        this.switchrequest = switchrequest;
    }

    @Column(name = "SWITCHRESPONSE", length = 128)
    public String getSwitchresponse() {
        return switchresponse;
    }

    public void setSwitchresponse(String switchresponse) {
        this.switchresponse = switchresponse;
    }

    @Column(name = "ADMINERRORLOG", length = 128)
    public String getAdminerrorlog() {
        return adminerrorlog;
    }

    public void setAdminerrorlog(String adminerrorlog) {
        this.adminerrorlog = adminerrorlog;
    }

    @Column(name = "SETTLEMENTFILEPATH", length = 128)
    public String getSettlementfilepath() {
        return this.settlementfilepath;
    }

    public void setSettlementfilepath(String settlementfilepath) {
        this.settlementfilepath = settlementfilepath;
    }
}
