package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgcountry generated by hbm2java
 */
@Entity
@Table(name = "IPGCOUNTRY" )
public class Ipgcountry implements java.io.Serializable {

    private String countrycode;
    private String description;
    private BigDecimal sortkey;
    private String countryisocode;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgtransaction> ipgtransactions = new HashSet<Ipgtransaction>(0);
    private Set<Ipgheadmerchant> ipgheadmerchants = new HashSet<Ipgheadmerchant>(0);
    private Set<Ipgriskprofileblockedcountry> ipgriskprofileblockedcountries = new HashSet<Ipgriskprofileblockedcountry>(0);
    private Set<Ipgmerchant> ipgmerchants = new HashSet<Ipgmerchant>(0);
    private Set<Epictxnrequests> epictxnrequestses = new HashSet<Epictxnrequests>(0);

    public Ipgcountry() {
    }

    public Ipgcountry(String countrycode, String description) {
        this.countrycode = countrycode;
        this.description = description;
    }

    public Ipgcountry(String countrycode, String description, Set<Ipgmerchant> ipgmerchants, BigDecimal sortkey, String countryisocode, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgtransaction> ipgtransactions, Set<Ipgheadmerchant> ipgheadmerchants, Set<Ipgriskprofileblockedcountry> ipgriskprofileblockedcountries, Set<Epictxnrequests> epictxnrequestses) {
        this.countrycode = countrycode;
        this.description = description;
        this.sortkey = sortkey;
        this.countryisocode = countryisocode;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgtransactions = ipgtransactions;
        this.ipgheadmerchants = ipgheadmerchants;
        this.ipgmerchants = ipgmerchants;
        this.epictxnrequestses = epictxnrequestses;
        this.ipgriskprofileblockedcountries = ipgriskprofileblockedcountries;
    }

    @Id
    @Column(name = "COUNTRYCODE", unique = true, nullable = false, length = 8)
    public String getCountrycode() {
        return this.countrycode;
    }

    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    @Column(name = "DESCRIPTION", nullable = false)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "SORTKEY", precision = 22, scale = 0)
    public BigDecimal getSortkey() {
        return this.sortkey;
    }

    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }

    @Column(name = "COUNTRYISOCODE", length = 20)
    public String getCountryisocode() {
        return this.countryisocode;
    }

    public void setCountryisocode(String countryisocode) {
        this.countryisocode = countryisocode;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcountry")
    public Set<Ipgtransaction> getIpgtransactions() {
        return this.ipgtransactions;
    }

    public void setIpgtransactions(Set<Ipgtransaction> ipgtransactions) {
        this.ipgtransactions = ipgtransactions;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcountry")
    public Set<Ipgheadmerchant> getIpgheadmerchants() {
        return this.ipgheadmerchants;
    }

    public void setIpgheadmerchants(Set<Ipgheadmerchant> ipgheadmerchants) {
        this.ipgheadmerchants = ipgheadmerchants;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcountry")
    public Set<Ipgriskprofileblockedcountry> getIpgriskprofileblockedcountries() {
        return this.ipgriskprofileblockedcountries;
    }

    public void setIpgriskprofileblockedcountries(Set<Ipgriskprofileblockedcountry> ipgriskprofileblockedcountries) {
        this.ipgriskprofileblockedcountries = ipgriskprofileblockedcountries;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcountry")
    public Set<Ipgmerchant> getIpgmerchants() {
        return this.ipgmerchants;
    }

    public void setIpgmerchants(Set<Ipgmerchant> ipgmerchants) {
        this.ipgmerchants = ipgmerchants;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcountry")
    public Set<Epictxnrequests> getEpictxnrequestses() {
        return this.epictxnrequestses;
    }

    public void setEpictxnrequestses(Set<Epictxnrequests> epictxnrequestses) {
        this.epictxnrequestses = epictxnrequestses;
    }
}
