package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ipgccbafile generated by hbm2java
 */
@Entity
@Table(name = "IPGCCBAFILE" , uniqueConstraints = @UniqueConstraint(columnNames = "FILENAME")
)
public class Ipgccbafile implements java.io.Serializable {

    private BigDecimal fileid;
    private Ipgstatus ipgstatus;
    private String filename;
    private Date starttime;
    private Date endtime;
    private String transactioncategory;
    private String lastupdateduser;
    private Date lastupdateddate;
    private Date createtime;
    private String remarks;

    public Ipgccbafile() {
    }

    public Ipgccbafile(BigDecimal fileid) {
        this.fileid = fileid;
    }

    public Ipgccbafile(BigDecimal fileid, Ipgstatus ipgstatus, String filename, Date starttime, Date endtime, String transactioncategory, String lastupdateduser, Date lastupdateddate, Date createtime, String remarks) {
        this.fileid = fileid;
        this.ipgstatus = ipgstatus;
        this.filename = filename;
        this.starttime = starttime;
        this.endtime = endtime;
        this.transactioncategory = transactioncategory;
        this.lastupdateduser = lastupdateduser;
        this.lastupdateddate = lastupdateddate;
        this.createtime = createtime;
        this.remarks = remarks;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGCCBAFILEID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name = "FILEID", unique = true, nullable = false, length = 8)
    public BigDecimal getFileid() {
        return this.fileid;
    }

    public void setFileid(BigDecimal fileid) {
        this.fileid = fileid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    @Column(name = "FILENAME", unique = true, length = 32)
    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "STARTTIME", length = 7)
    public Date getStarttime() {
        return this.starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ENDTIME", length = 7)
    public Date getEndtime() {
        return this.endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    @Column(name = "TRANSACTIONCATEGORY", length = 32)
    public String getTransactioncategory() {
        return this.transactioncategory;
    }

    public void setTransactioncategory(String transactioncategory) {
        this.transactioncategory = transactioncategory;
    }

    @Column(name = "LASTUPDATEDUSER", length = 32)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDDATE", length = 7)
    public Date getLastupdateddate() {
        return this.lastupdateddate;
    }

    public void setLastupdateddate(Date lastupdateddate) {
        this.lastupdateddate = lastupdateddate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATETIME", length = 7)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Column(name = "REMARKS", length = 32)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
