package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgcurrency generated by hbm2java
 */
@Entity
@Table(name = "IPGCURRENCY" )
public class Ipgcurrency implements java.io.Serializable {

    private String currencyisocode;
    private String currencycode;
    private String description;
    private BigDecimal sortkey;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgtransaction> ipgtransactions = new HashSet<Ipgtransaction>(0);
    private Set<Ipgmerchnatterminal> ipgmerchnatterminals = new HashSet<Ipgmerchnatterminal>(0);
    private Set<Ipgccbatransaction> ipgccbatransactions = new HashSet<Ipgccbatransaction>(0);
    private Set<Ipgservicecharge> ipgservicecharges = new HashSet<Ipgservicecharge>(0);
    private Set<Ipgriskprofileblockedcurrency> ipgriskprofileblockedcurrencies = new HashSet<Ipgriskprofileblockedcurrency>(0);
    private Set<Ipgmerchantcurrency> ipgmerchantcurrencies = new HashSet<Ipgmerchantcurrency>(0);
    private Set<Epictxnrequests> epictxnrequestses = new HashSet<Epictxnrequests>(0);

    public Ipgcurrency() {
    }

    public Ipgcurrency(String currencyisocode, String currencycode) {
        this.currencyisocode = currencyisocode;
        this.currencycode = currencycode;
    }

    public Ipgcurrency(String currencyisocode, String currencycode, String description, BigDecimal sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgtransaction> ipgtransactions, Set<Ipgmerchnatterminal> ipgmerchnatterminals, Set<Ipgccbatransaction> ipgccbatransactions, Set<Ipgservicecharge> ipgservicecharges, Set<Ipgriskprofileblockedcurrency> ipgriskprofileblockedcurrencies, Set<Ipgmerchantcurrency> ipgmerchantcurrencies, Set<Epictxnrequests> epictxnrequestses) {
        this.currencyisocode = currencyisocode;
        this.currencycode = currencycode;
        this.description = description;
        this.sortkey = sortkey;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgtransactions = ipgtransactions;
        this.ipgmerchnatterminals = ipgmerchnatterminals;
        this.ipgccbatransactions = ipgccbatransactions;
        this.ipgservicecharges = ipgservicecharges;
        this.ipgriskprofileblockedcurrencies = ipgriskprofileblockedcurrencies;
        this.ipgmerchantcurrencies = ipgmerchantcurrencies;
        this.epictxnrequestses = epictxnrequestses;
    }

    @Id
    @Column(name = "CURRENCYISOCODE", unique = true, nullable = false, length = 8)
    public String getCurrencyisocode() {
        return this.currencyisocode;
    }

    public void setCurrencyisocode(String currencyisocode) {
        this.currencyisocode = currencyisocode;
    }

    @Column(name = "CURRENCYCODE", nullable = false, length = 8)
    public String getCurrencycode() {
        return this.currencycode;
    }

    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "SORTKEY", precision = 22, scale = 0)
    public BigDecimal getSortkey() {
        return this.sortkey;
    }

    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Ipgtransaction> getIpgtransactions() {
        return this.ipgtransactions;
    }

    public void setIpgtransactions(Set<Ipgtransaction> ipgtransactions) {
        this.ipgtransactions = ipgtransactions;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Ipgmerchnatterminal> getIpgmerchnatterminals() {
        return this.ipgmerchnatterminals;
    }

    public void setIpgmerchnatterminals(Set<Ipgmerchnatterminal> ipgmerchnatterminals) {
        this.ipgmerchnatterminals = ipgmerchnatterminals;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Ipgccbatransaction> getIpgccbatransactions() {
        return this.ipgccbatransactions;
    }

    public void setIpgccbatransactions(Set<Ipgccbatransaction> ipgccbatransactions) {
        this.ipgccbatransactions = ipgccbatransactions;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Ipgservicecharge> getIpgservicecharges() {
        return this.ipgservicecharges;
    }

    public void setIpgservicecharges(Set<Ipgservicecharge> ipgservicecharges) {
        this.ipgservicecharges = ipgservicecharges;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Ipgriskprofileblockedcurrency> getIpgriskprofileblockedcurrencies() {
        return this.ipgriskprofileblockedcurrencies;
    }

    public void setIpgriskprofileblockedcurrencies(Set<Ipgriskprofileblockedcurrency> ipgriskprofileblockedcurrencies) {
        this.ipgriskprofileblockedcurrencies = ipgriskprofileblockedcurrencies;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Ipgmerchantcurrency> getIpgmerchantcurrencies() {
        return this.ipgmerchantcurrencies;
    }

    public void setIpgmerchantcurrencies(Set<Ipgmerchantcurrency> ipgmerchantcurrencies) {
        this.ipgmerchantcurrencies = ipgmerchantcurrencies;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgcurrency")
    public Set<Epictxnrequests> getEpictxnrequestses() {
        return this.epictxnrequestses;
    }

    public void setEpictxnrequestses(Set<Epictxnrequests> epictxnrequestses) {
        this.epictxnrequestses = epictxnrequestses;
    }
}
