package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgccbatransaction generated by hbm2java
 */
@Entity
@Table(name="IPGCCBATRANSACTION"
    
)
public class Ipgccbatransaction  implements java.io.Serializable {


     private BigDecimal id;
     private Ipgcurrency ipgcurrency;
     private String fileid;
     private String cardnumber;
     private String expirydate;
     private String nicno;
     private String amount;
     private BigDecimal noofinstallment;
     private String recurringperiod;
     private BigDecimal count;
     private Date nextdate;
     private String transactionid;
     private String responsecode;

    public Ipgccbatransaction() {
    }

	
    public Ipgccbatransaction(BigDecimal id) {
        this.id = id;
    }
    public Ipgccbatransaction(BigDecimal id, Ipgcurrency ipgcurrency, String fileid, String cardnumber, String expirydate, String nicno, String amount, BigDecimal noofinstallment, String recurringperiod, BigDecimal count, Date nextdate, String transactionid, String responsecode) {
       this.id = id;
       this.ipgcurrency = ipgcurrency;
       this.fileid = fileid;
       this.cardnumber = cardnumber;
       this.expirydate = expirydate;
       this.nicno = nicno;
       this.amount = amount;
       this.noofinstallment = noofinstallment;
       this.recurringperiod = recurringperiod;
       this.count = count;
       this.nextdate = nextdate;
       this.transactionid = transactionid;
       this.responsecode = responsecode;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURRENCY")
    public Ipgcurrency getIpgcurrency() {
        return this.ipgcurrency;
    }
    
    public void setIpgcurrency(Ipgcurrency ipgcurrency) {
        this.ipgcurrency = ipgcurrency;
    }
    
    @Column(name="FILEID", length=8)
    public String getFileid() {
        return this.fileid;
    }
    
    public void setFileid(String fileid) {
        this.fileid = fileid;
    }
    
    @Column(name="CARDNUMBER", length=20)
    public String getCardnumber() {
        return this.cardnumber;
    }
    
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }
    
    @Column(name="EXPIRYDATE", length=5)
    public String getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(String expirydate) {
        this.expirydate = expirydate;
    }
    
    @Column(name="NICNO", length=10)
    public String getNicno() {
        return this.nicno;
    }
    
    public void setNicno(String nicno) {
        this.nicno = nicno;
    }
    
    @Column(name="AMOUNT", length=12)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    
    @Column(name="NOOFINSTALLMENT", precision=22, scale=0)
    public BigDecimal getNoofinstallment() {
        return this.noofinstallment;
    }
    
    public void setNoofinstallment(BigDecimal noofinstallment) {
        this.noofinstallment = noofinstallment;
    }
    
    @Column(name="RECURRINGPERIOD", length=4)
    public String getRecurringperiod() {
        return this.recurringperiod;
    }
    
    public void setRecurringperiod(String recurringperiod) {
        this.recurringperiod = recurringperiod;
    }
    
    @Column(name="COUNT", precision=22, scale=0)
    public BigDecimal getCount() {
        return this.count;
    }
    
    public void setCount(BigDecimal count) {
        this.count = count;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NEXTDATE", length=7)
    public Date getNextdate() {
        return this.nextdate;
    }
    
    public void setNextdate(Date nextdate) {
        this.nextdate = nextdate;
    }
    
    @Column(name="TRANSACTIONID", length=20)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }
    
    @Column(name="RESPONSECODE", length=2)
    public String getResponsecode() {
        return this.responsecode;
    }
    
    public void setResponsecode(String responsecode) {
        this.responsecode = responsecode;
    }




}


