package com.epic.epay.ipg.util.mapping;
// Generated 02/10/2014 7:08:43 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ipgecivalue generated by hbm2java
 */
@Entity
@Table(name="IPGECIVALUE")
public class Ipgecivalue  implements java.io.Serializable {


     private String value;

    public Ipgecivalue() {
    }

    public Ipgecivalue(String value) {
       this.value = value;
    }
   
     @Id 

    
    @Column(name="VALUE", unique=true, nullable=false, length=20)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


