package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ipgenginerequest generated by hbm2java
 */
@Entity
@Table(name="IPGENGINEREQUEST"
    
)
public class Ipgenginerequest  implements java.io.Serializable {


     private IpgenginerequestId id;

    public Ipgenginerequest() {
    }

    public Ipgenginerequest(IpgenginerequestId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="ipgtransactionid", column=@Column(name="IPGTRANSACTIONID", nullable=false, length=20) ), 
        @AttributeOverride(name="transactioncode", column=@Column(name="TRANSACTIONCODE", length=2) ), 
        @AttributeOverride(name="cardtype", column=@Column(name="CARDTYPE", length=10) ), 
        @AttributeOverride(name="mti", column=@Column(name="MTI", length=4) ), 
        @AttributeOverride(name="processingcode", column=@Column(name="PROCESSINGCODE", length=6) ), 
        @AttributeOverride(name="tid", column=@Column(name="TID", length=8) ), 
        @AttributeOverride(name="merchantid", column=@Column(name="MERCHANTID", length=15) ), 
        @AttributeOverride(name="cardnumber", column=@Column(name="CARDNUMBER", length=20) ), 
        @AttributeOverride(name="dateofexpiry", column=@Column(name="DATEOFEXPIRY", length=4) ), 
        @AttributeOverride(name="transactionamount", column=@Column(name="TRANSACTIONAMOUNT", precision=9, scale=0) ), 
        @AttributeOverride(name="localdate", column=@Column(name="LOCALDATE", length=4) ), 
        @AttributeOverride(name="localtime", column=@Column(name="LOCALTIME", length=6) ), 
        @AttributeOverride(name="tracenumber", column=@Column(name="TRACENUMBER", length=6) ), 
        @AttributeOverride(name="transactioninitiationdatetime", column=@Column(name="TRANSACTIONINITIATIONDATETIME", length=19) ), 
        @AttributeOverride(name="capturedate", column=@Column(name="CAPTUREDATE", length=4) ), 
        @AttributeOverride(name="cardacceptinl", column=@Column(name="CARDACCEPTINL", length=100) ), 
        @AttributeOverride(name="privateusage", column=@Column(name="PRIVATEUSAGE", length=100) ), 
        @AttributeOverride(name="mtype", column=@Column(name="MTYPE", length=4) ), 
        @AttributeOverride(name="aiic", column=@Column(name="AIIC", length=11) ), 
        @AttributeOverride(name="aicc", column=@Column(name="AICC", length=4) ), 
        @AttributeOverride(name="posem", column=@Column(name="POSEM", length=4) ), 
        @AttributeOverride(name="poscc", column=@Column(name="POSCC", length=2) ), 
        @AttributeOverride(name="nii", column=@Column(name="NII", length=3) ), 
        @AttributeOverride(name="eci", column=@Column(name="ECI", length=4) ), 
        @AttributeOverride(name="cavv", column=@Column(name="CAVV", length=32) ), 
        @AttributeOverride(name="cvv", column=@Column(name="CVV", length=4) ), 
        @AttributeOverride(name="currencycode", column=@Column(name="CURRENCYCODE", length=3) ), 
        @AttributeOverride(name="countrycode", column=@Column(name="COUNTRYCODE", length=3) ), 
        @AttributeOverride(name="responcecode", column=@Column(name="RESPONCECODE", length=4) ), 
        @AttributeOverride(name="batchno", column=@Column(name="BATCHNO", length=6) ), 
        @AttributeOverride(name="rrn", column=@Column(name="RRN", length=12) ), 
        @AttributeOverride(name="approvalcode", column=@Column(name="APPROVALCODE", length=6) ), 
        @AttributeOverride(name="settlementamount", column=@Column(name="SETTLEMENTAMOUNT", length=12) ), 
        @AttributeOverride(name="settlementcount", column=@Column(name="SETTLEMENTCOUNT", length=12) ), 
        @AttributeOverride(name="saledatetime", column=@Column(name="SALEDATETIME", length=25) ), 
        @AttributeOverride(name="voiddatetime", column=@Column(name="VOIDDATETIME", length=25) ), 
        @AttributeOverride(name="reversdatetime", column=@Column(name="REVERSDATETIME", length=25) ), 
        @AttributeOverride(name="settlementdatetime", column=@Column(name="SETTLEMENTDATETIME", length=25) ), 
        @AttributeOverride(name="statuscode", column=@Column(name="STATUSCODE", length=5) ), 
        @AttributeOverride(name="lastupdatedtime", column=@Column(name="LASTUPDATEDTIME", length=11) ), 
        @AttributeOverride(name="refunddatetime", column=@Column(name="REFUNDDATETIME", length=25) ), 
        @AttributeOverride(name="motodatetime", column=@Column(name="MOTODATETIME", length=25) ) } )
    public IpgenginerequestId getId() {
        return this.id;
    }
    
    public void setId(IpgenginerequestId id) {
        this.id = id;
    }




}


