package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgenginerequestId generated by hbm2java
 */
@Embeddable
public class IpgenginerequestId  implements java.io.Serializable {


     private String ipgtransactionid;
     private String transactioncode;
     private String cardtype;
     private String mti;
     private String processingcode;
     private String tid;
     private String merchantid;
     private String cardnumber;
     private String dateofexpiry;
     private Integer transactionamount;
     private String localdate;
     private String localtime;
     private String tracenumber;
     private String transactioninitiationdatetime;
     private String capturedate;
     private String cardacceptinl;
     private String privateusage;
     private String mtype;
     private String aiic;
     private String aicc;
     private String posem;
     private String poscc;
     private String nii;
     private String eci;
     private String cavv;
     private String cvv;
     private String currencycode;
     private String countrycode;
     private String responcecode;
     private String batchno;
     private String rrn;
     private String approvalcode;
     private String settlementamount;
     private String settlementcount;
     private String saledatetime;
     private String voiddatetime;
     private String reversdatetime;
     private String settlementdatetime;
     private String statuscode;
     private Date lastupdatedtime;
     private String refunddatetime;
     private String motodatetime;

    public IpgenginerequestId() {
    }

	
    public IpgenginerequestId(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }
    public IpgenginerequestId(String ipgtransactionid, String transactioncode, String cardtype, String mti, String processingcode, String tid, String merchantid, String cardnumber, String dateofexpiry, Integer transactionamount, String localdate, String localtime, String tracenumber, String transactioninitiationdatetime, String capturedate, String cardacceptinl, String privateusage, String mtype, String aiic, String aicc, String posem, String poscc, String nii, String eci, String cavv, String cvv, String currencycode, String countrycode, String responcecode, String batchno, String rrn, String approvalcode, String settlementamount, String settlementcount, String saledatetime, String voiddatetime, String reversdatetime, String settlementdatetime, String statuscode, Date lastupdatedtime, String refunddatetime, String motodatetime) {
       this.ipgtransactionid = ipgtransactionid;
       this.transactioncode = transactioncode;
       this.cardtype = cardtype;
       this.mti = mti;
       this.processingcode = processingcode;
       this.tid = tid;
       this.merchantid = merchantid;
       this.cardnumber = cardnumber;
       this.dateofexpiry = dateofexpiry;
       this.transactionamount = transactionamount;
       this.localdate = localdate;
       this.localtime = localtime;
       this.tracenumber = tracenumber;
       this.transactioninitiationdatetime = transactioninitiationdatetime;
       this.capturedate = capturedate;
       this.cardacceptinl = cardacceptinl;
       this.privateusage = privateusage;
       this.mtype = mtype;
       this.aiic = aiic;
       this.aicc = aicc;
       this.posem = posem;
       this.poscc = poscc;
       this.nii = nii;
       this.eci = eci;
       this.cavv = cavv;
       this.cvv = cvv;
       this.currencycode = currencycode;
       this.countrycode = countrycode;
       this.responcecode = responcecode;
       this.batchno = batchno;
       this.rrn = rrn;
       this.approvalcode = approvalcode;
       this.settlementamount = settlementamount;
       this.settlementcount = settlementcount;
       this.saledatetime = saledatetime;
       this.voiddatetime = voiddatetime;
       this.reversdatetime = reversdatetime;
       this.settlementdatetime = settlementdatetime;
       this.statuscode = statuscode;
       this.lastupdatedtime = lastupdatedtime;
       this.refunddatetime = refunddatetime;
       this.motodatetime = motodatetime;
    }
   

    @Column(name="IPGTRANSACTIONID", nullable=false, length=20)
    public String getIpgtransactionid() {
        return this.ipgtransactionid;
    }
    
    public void setIpgtransactionid(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }

    @Column(name="TRANSACTIONCODE", length=2)
    public String getTransactioncode() {
        return this.transactioncode;
    }
    
    public void setTransactioncode(String transactioncode) {
        this.transactioncode = transactioncode;
    }

    @Column(name="CARDTYPE", length=10)
    public String getCardtype() {
        return this.cardtype;
    }
    
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    @Column(name="MTI", length=4)
    public String getMti() {
        return this.mti;
    }
    
    public void setMti(String mti) {
        this.mti = mti;
    }

    @Column(name="PROCESSINGCODE", length=6)
    public String getProcessingcode() {
        return this.processingcode;
    }
    
    public void setProcessingcode(String processingcode) {
        this.processingcode = processingcode;
    }

    @Column(name="TID", length=8)
    public String getTid() {
        return this.tid;
    }
    
    public void setTid(String tid) {
        this.tid = tid;
    }

    @Column(name="MERCHANTID", length=15)
    public String getMerchantid() {
        return this.merchantid;
    }
    
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    @Column(name="CARDNUMBER", length=20)
    public String getCardnumber() {
        return this.cardnumber;
    }
    
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }

    @Column(name="DATEOFEXPIRY", length=4)
    public String getDateofexpiry() {
        return this.dateofexpiry;
    }
    
    public void setDateofexpiry(String dateofexpiry) {
        this.dateofexpiry = dateofexpiry;
    }

    @Column(name="TRANSACTIONAMOUNT", precision=9, scale=0)
    public Integer getTransactionamount() {
        return this.transactionamount;
    }
    
    public void setTransactionamount(Integer transactionamount) {
        this.transactionamount = transactionamount;
    }

    @Column(name="LOCALDATE", length=4)
    public String getLocaldate() {
        return this.localdate;
    }
    
    public void setLocaldate(String localdate) {
        this.localdate = localdate;
    }

    @Column(name="LOCALTIME", length=6)
    public String getLocaltime() {
        return this.localtime;
    }
    
    public void setLocaltime(String localtime) {
        this.localtime = localtime;
    }

    @Column(name="TRACENUMBER", length=6)
    public String getTracenumber() {
        return this.tracenumber;
    }
    
    public void setTracenumber(String tracenumber) {
        this.tracenumber = tracenumber;
    }

    @Column(name="TRANSACTIONINITIATIONDATETIME", length=19)
    public String getTransactioninitiationdatetime() {
        return this.transactioninitiationdatetime;
    }
    
    public void setTransactioninitiationdatetime(String transactioninitiationdatetime) {
        this.transactioninitiationdatetime = transactioninitiationdatetime;
    }

    @Column(name="CAPTUREDATE", length=4)
    public String getCapturedate() {
        return this.capturedate;
    }
    
    public void setCapturedate(String capturedate) {
        this.capturedate = capturedate;
    }

    @Column(name="CARDACCEPTINL", length=100)
    public String getCardacceptinl() {
        return this.cardacceptinl;
    }
    
    public void setCardacceptinl(String cardacceptinl) {
        this.cardacceptinl = cardacceptinl;
    }

    @Column(name="PRIVATEUSAGE", length=100)
    public String getPrivateusage() {
        return this.privateusage;
    }
    
    public void setPrivateusage(String privateusage) {
        this.privateusage = privateusage;
    }

    @Column(name="MTYPE", length=4)
    public String getMtype() {
        return this.mtype;
    }
    
    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    @Column(name="AIIC", length=11)
    public String getAiic() {
        return this.aiic;
    }
    
    public void setAiic(String aiic) {
        this.aiic = aiic;
    }

    @Column(name="AICC", length=4)
    public String getAicc() {
        return this.aicc;
    }
    
    public void setAicc(String aicc) {
        this.aicc = aicc;
    }

    @Column(name="POSEM", length=4)
    public String getPosem() {
        return this.posem;
    }
    
    public void setPosem(String posem) {
        this.posem = posem;
    }

    @Column(name="POSCC", length=2)
    public String getPoscc() {
        return this.poscc;
    }
    
    public void setPoscc(String poscc) {
        this.poscc = poscc;
    }

    @Column(name="NII", length=3)
    public String getNii() {
        return this.nii;
    }
    
    public void setNii(String nii) {
        this.nii = nii;
    }

    @Column(name="ECI", length=4)
    public String getEci() {
        return this.eci;
    }
    
    public void setEci(String eci) {
        this.eci = eci;
    }

    @Column(name="CAVV", length=32)
    public String getCavv() {
        return this.cavv;
    }
    
    public void setCavv(String cavv) {
        this.cavv = cavv;
    }

    @Column(name="CVV", length=4)
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    @Column(name="CURRENCYCODE", length=3)
    public String getCurrencycode() {
        return this.currencycode;
    }
    
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }

    @Column(name="COUNTRYCODE", length=3)
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    @Column(name="RESPONCECODE", length=4)
    public String getResponcecode() {
        return this.responcecode;
    }
    
    public void setResponcecode(String responcecode) {
        this.responcecode = responcecode;
    }

    @Column(name="BATCHNO", length=6)
    public String getBatchno() {
        return this.batchno;
    }
    
    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    @Column(name="RRN", length=12)
    public String getRrn() {
        return this.rrn;
    }
    
    public void setRrn(String rrn) {
        this.rrn = rrn;
    }

    @Column(name="APPROVALCODE", length=6)
    public String getApprovalcode() {
        return this.approvalcode;
    }
    
    public void setApprovalcode(String approvalcode) {
        this.approvalcode = approvalcode;
    }

    @Column(name="SETTLEMENTAMOUNT", length=12)
    public String getSettlementamount() {
        return this.settlementamount;
    }
    
    public void setSettlementamount(String settlementamount) {
        this.settlementamount = settlementamount;
    }

    @Column(name="SETTLEMENTCOUNT", length=12)
    public String getSettlementcount() {
        return this.settlementcount;
    }
    
    public void setSettlementcount(String settlementcount) {
        this.settlementcount = settlementcount;
    }

    @Column(name="SALEDATETIME", length=25)
    public String getSaledatetime() {
        return this.saledatetime;
    }
    
    public void setSaledatetime(String saledatetime) {
        this.saledatetime = saledatetime;
    }

    @Column(name="VOIDDATETIME", length=25)
    public String getVoiddatetime() {
        return this.voiddatetime;
    }
    
    public void setVoiddatetime(String voiddatetime) {
        this.voiddatetime = voiddatetime;
    }

    @Column(name="REVERSDATETIME", length=25)
    public String getReversdatetime() {
        return this.reversdatetime;
    }
    
    public void setReversdatetime(String reversdatetime) {
        this.reversdatetime = reversdatetime;
    }

    @Column(name="SETTLEMENTDATETIME", length=25)
    public String getSettlementdatetime() {
        return this.settlementdatetime;
    }
    
    public void setSettlementdatetime(String settlementdatetime) {
        this.settlementdatetime = settlementdatetime;
    }

    @Column(name="STATUSCODE", length=5)
    public String getStatuscode() {
        return this.statuscode;
    }
    
    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    @Column(name="LASTUPDATEDTIME", length=11)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Column(name="REFUNDDATETIME", length=25)
    public String getRefunddatetime() {
        return this.refunddatetime;
    }
    
    public void setRefunddatetime(String refunddatetime) {
        this.refunddatetime = refunddatetime;
    }

    @Column(name="MOTODATETIME", length=25)
    public String getMotodatetime() {
        return this.motodatetime;
    }
    
    public void setMotodatetime(String motodatetime) {
        this.motodatetime = motodatetime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgenginerequestId) ) return false;
		 IpgenginerequestId castOther = ( IpgenginerequestId ) other; 
         
		 return ( (this.getIpgtransactionid()==castOther.getIpgtransactionid()) || ( this.getIpgtransactionid()!=null && castOther.getIpgtransactionid()!=null && this.getIpgtransactionid().equals(castOther.getIpgtransactionid()) ) )
 && ( (this.getTransactioncode()==castOther.getTransactioncode()) || ( this.getTransactioncode()!=null && castOther.getTransactioncode()!=null && this.getTransactioncode().equals(castOther.getTransactioncode()) ) )
 && ( (this.getCardtype()==castOther.getCardtype()) || ( this.getCardtype()!=null && castOther.getCardtype()!=null && this.getCardtype().equals(castOther.getCardtype()) ) )
 && ( (this.getMti()==castOther.getMti()) || ( this.getMti()!=null && castOther.getMti()!=null && this.getMti().equals(castOther.getMti()) ) )
 && ( (this.getProcessingcode()==castOther.getProcessingcode()) || ( this.getProcessingcode()!=null && castOther.getProcessingcode()!=null && this.getProcessingcode().equals(castOther.getProcessingcode()) ) )
 && ( (this.getTid()==castOther.getTid()) || ( this.getTid()!=null && castOther.getTid()!=null && this.getTid().equals(castOther.getTid()) ) )
 && ( (this.getMerchantid()==castOther.getMerchantid()) || ( this.getMerchantid()!=null && castOther.getMerchantid()!=null && this.getMerchantid().equals(castOther.getMerchantid()) ) )
 && ( (this.getCardnumber()==castOther.getCardnumber()) || ( this.getCardnumber()!=null && castOther.getCardnumber()!=null && this.getCardnumber().equals(castOther.getCardnumber()) ) )
 && ( (this.getDateofexpiry()==castOther.getDateofexpiry()) || ( this.getDateofexpiry()!=null && castOther.getDateofexpiry()!=null && this.getDateofexpiry().equals(castOther.getDateofexpiry()) ) )
 && ( (this.getTransactionamount()==castOther.getTransactionamount()) || ( this.getTransactionamount()!=null && castOther.getTransactionamount()!=null && this.getTransactionamount().equals(castOther.getTransactionamount()) ) )
 && ( (this.getLocaldate()==castOther.getLocaldate()) || ( this.getLocaldate()!=null && castOther.getLocaldate()!=null && this.getLocaldate().equals(castOther.getLocaldate()) ) )
 && ( (this.getLocaltime()==castOther.getLocaltime()) || ( this.getLocaltime()!=null && castOther.getLocaltime()!=null && this.getLocaltime().equals(castOther.getLocaltime()) ) )
 && ( (this.getTracenumber()==castOther.getTracenumber()) || ( this.getTracenumber()!=null && castOther.getTracenumber()!=null && this.getTracenumber().equals(castOther.getTracenumber()) ) )
 && ( (this.getTransactioninitiationdatetime()==castOther.getTransactioninitiationdatetime()) || ( this.getTransactioninitiationdatetime()!=null && castOther.getTransactioninitiationdatetime()!=null && this.getTransactioninitiationdatetime().equals(castOther.getTransactioninitiationdatetime()) ) )
 && ( (this.getCapturedate()==castOther.getCapturedate()) || ( this.getCapturedate()!=null && castOther.getCapturedate()!=null && this.getCapturedate().equals(castOther.getCapturedate()) ) )
 && ( (this.getCardacceptinl()==castOther.getCardacceptinl()) || ( this.getCardacceptinl()!=null && castOther.getCardacceptinl()!=null && this.getCardacceptinl().equals(castOther.getCardacceptinl()) ) )
 && ( (this.getPrivateusage()==castOther.getPrivateusage()) || ( this.getPrivateusage()!=null && castOther.getPrivateusage()!=null && this.getPrivateusage().equals(castOther.getPrivateusage()) ) )
 && ( (this.getMtype()==castOther.getMtype()) || ( this.getMtype()!=null && castOther.getMtype()!=null && this.getMtype().equals(castOther.getMtype()) ) )
 && ( (this.getAiic()==castOther.getAiic()) || ( this.getAiic()!=null && castOther.getAiic()!=null && this.getAiic().equals(castOther.getAiic()) ) )
 && ( (this.getAicc()==castOther.getAicc()) || ( this.getAicc()!=null && castOther.getAicc()!=null && this.getAicc().equals(castOther.getAicc()) ) )
 && ( (this.getPosem()==castOther.getPosem()) || ( this.getPosem()!=null && castOther.getPosem()!=null && this.getPosem().equals(castOther.getPosem()) ) )
 && ( (this.getPoscc()==castOther.getPoscc()) || ( this.getPoscc()!=null && castOther.getPoscc()!=null && this.getPoscc().equals(castOther.getPoscc()) ) )
 && ( (this.getNii()==castOther.getNii()) || ( this.getNii()!=null && castOther.getNii()!=null && this.getNii().equals(castOther.getNii()) ) )
 && ( (this.getEci()==castOther.getEci()) || ( this.getEci()!=null && castOther.getEci()!=null && this.getEci().equals(castOther.getEci()) ) )
 && ( (this.getCavv()==castOther.getCavv()) || ( this.getCavv()!=null && castOther.getCavv()!=null && this.getCavv().equals(castOther.getCavv()) ) )
 && ( (this.getCvv()==castOther.getCvv()) || ( this.getCvv()!=null && castOther.getCvv()!=null && this.getCvv().equals(castOther.getCvv()) ) )
 && ( (this.getCurrencycode()==castOther.getCurrencycode()) || ( this.getCurrencycode()!=null && castOther.getCurrencycode()!=null && this.getCurrencycode().equals(castOther.getCurrencycode()) ) )
 && ( (this.getCountrycode()==castOther.getCountrycode()) || ( this.getCountrycode()!=null && castOther.getCountrycode()!=null && this.getCountrycode().equals(castOther.getCountrycode()) ) )
 && ( (this.getResponcecode()==castOther.getResponcecode()) || ( this.getResponcecode()!=null && castOther.getResponcecode()!=null && this.getResponcecode().equals(castOther.getResponcecode()) ) )
 && ( (this.getBatchno()==castOther.getBatchno()) || ( this.getBatchno()!=null && castOther.getBatchno()!=null && this.getBatchno().equals(castOther.getBatchno()) ) )
 && ( (this.getRrn()==castOther.getRrn()) || ( this.getRrn()!=null && castOther.getRrn()!=null && this.getRrn().equals(castOther.getRrn()) ) )
 && ( (this.getApprovalcode()==castOther.getApprovalcode()) || ( this.getApprovalcode()!=null && castOther.getApprovalcode()!=null && this.getApprovalcode().equals(castOther.getApprovalcode()) ) )
 && ( (this.getSettlementamount()==castOther.getSettlementamount()) || ( this.getSettlementamount()!=null && castOther.getSettlementamount()!=null && this.getSettlementamount().equals(castOther.getSettlementamount()) ) )
 && ( (this.getSettlementcount()==castOther.getSettlementcount()) || ( this.getSettlementcount()!=null && castOther.getSettlementcount()!=null && this.getSettlementcount().equals(castOther.getSettlementcount()) ) )
 && ( (this.getSaledatetime()==castOther.getSaledatetime()) || ( this.getSaledatetime()!=null && castOther.getSaledatetime()!=null && this.getSaledatetime().equals(castOther.getSaledatetime()) ) )
 && ( (this.getVoiddatetime()==castOther.getVoiddatetime()) || ( this.getVoiddatetime()!=null && castOther.getVoiddatetime()!=null && this.getVoiddatetime().equals(castOther.getVoiddatetime()) ) )
 && ( (this.getReversdatetime()==castOther.getReversdatetime()) || ( this.getReversdatetime()!=null && castOther.getReversdatetime()!=null && this.getReversdatetime().equals(castOther.getReversdatetime()) ) )
 && ( (this.getSettlementdatetime()==castOther.getSettlementdatetime()) || ( this.getSettlementdatetime()!=null && castOther.getSettlementdatetime()!=null && this.getSettlementdatetime().equals(castOther.getSettlementdatetime()) ) )
 && ( (this.getStatuscode()==castOther.getStatuscode()) || ( this.getStatuscode()!=null && castOther.getStatuscode()!=null && this.getStatuscode().equals(castOther.getStatuscode()) ) )
 && ( (this.getLastupdatedtime()==castOther.getLastupdatedtime()) || ( this.getLastupdatedtime()!=null && castOther.getLastupdatedtime()!=null && this.getLastupdatedtime().equals(castOther.getLastupdatedtime()) ) )
 && ( (this.getRefunddatetime()==castOther.getRefunddatetime()) || ( this.getRefunddatetime()!=null && castOther.getRefunddatetime()!=null && this.getRefunddatetime().equals(castOther.getRefunddatetime()) ) )
 && ( (this.getMotodatetime()==castOther.getMotodatetime()) || ( this.getMotodatetime()!=null && castOther.getMotodatetime()!=null && this.getMotodatetime().equals(castOther.getMotodatetime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIpgtransactionid() == null ? 0 : this.getIpgtransactionid().hashCode() );
         result = 37 * result + ( getTransactioncode() == null ? 0 : this.getTransactioncode().hashCode() );
         result = 37 * result + ( getCardtype() == null ? 0 : this.getCardtype().hashCode() );
         result = 37 * result + ( getMti() == null ? 0 : this.getMti().hashCode() );
         result = 37 * result + ( getProcessingcode() == null ? 0 : this.getProcessingcode().hashCode() );
         result = 37 * result + ( getTid() == null ? 0 : this.getTid().hashCode() );
         result = 37 * result + ( getMerchantid() == null ? 0 : this.getMerchantid().hashCode() );
         result = 37 * result + ( getCardnumber() == null ? 0 : this.getCardnumber().hashCode() );
         result = 37 * result + ( getDateofexpiry() == null ? 0 : this.getDateofexpiry().hashCode() );
         result = 37 * result + ( getTransactionamount() == null ? 0 : this.getTransactionamount().hashCode() );
         result = 37 * result + ( getLocaldate() == null ? 0 : this.getLocaldate().hashCode() );
         result = 37 * result + ( getLocaltime() == null ? 0 : this.getLocaltime().hashCode() );
         result = 37 * result + ( getTracenumber() == null ? 0 : this.getTracenumber().hashCode() );
         result = 37 * result + ( getTransactioninitiationdatetime() == null ? 0 : this.getTransactioninitiationdatetime().hashCode() );
         result = 37 * result + ( getCapturedate() == null ? 0 : this.getCapturedate().hashCode() );
         result = 37 * result + ( getCardacceptinl() == null ? 0 : this.getCardacceptinl().hashCode() );
         result = 37 * result + ( getPrivateusage() == null ? 0 : this.getPrivateusage().hashCode() );
         result = 37 * result + ( getMtype() == null ? 0 : this.getMtype().hashCode() );
         result = 37 * result + ( getAiic() == null ? 0 : this.getAiic().hashCode() );
         result = 37 * result + ( getAicc() == null ? 0 : this.getAicc().hashCode() );
         result = 37 * result + ( getPosem() == null ? 0 : this.getPosem().hashCode() );
         result = 37 * result + ( getPoscc() == null ? 0 : this.getPoscc().hashCode() );
         result = 37 * result + ( getNii() == null ? 0 : this.getNii().hashCode() );
         result = 37 * result + ( getEci() == null ? 0 : this.getEci().hashCode() );
         result = 37 * result + ( getCavv() == null ? 0 : this.getCavv().hashCode() );
         result = 37 * result + ( getCvv() == null ? 0 : this.getCvv().hashCode() );
         result = 37 * result + ( getCurrencycode() == null ? 0 : this.getCurrencycode().hashCode() );
         result = 37 * result + ( getCountrycode() == null ? 0 : this.getCountrycode().hashCode() );
         result = 37 * result + ( getResponcecode() == null ? 0 : this.getResponcecode().hashCode() );
         result = 37 * result + ( getBatchno() == null ? 0 : this.getBatchno().hashCode() );
         result = 37 * result + ( getRrn() == null ? 0 : this.getRrn().hashCode() );
         result = 37 * result + ( getApprovalcode() == null ? 0 : this.getApprovalcode().hashCode() );
         result = 37 * result + ( getSettlementamount() == null ? 0 : this.getSettlementamount().hashCode() );
         result = 37 * result + ( getSettlementcount() == null ? 0 : this.getSettlementcount().hashCode() );
         result = 37 * result + ( getSaledatetime() == null ? 0 : this.getSaledatetime().hashCode() );
         result = 37 * result + ( getVoiddatetime() == null ? 0 : this.getVoiddatetime().hashCode() );
         result = 37 * result + ( getReversdatetime() == null ? 0 : this.getReversdatetime().hashCode() );
         result = 37 * result + ( getSettlementdatetime() == null ? 0 : this.getSettlementdatetime().hashCode() );
         result = 37 * result + ( getStatuscode() == null ? 0 : this.getStatuscode().hashCode() );
         result = 37 * result + ( getLastupdatedtime() == null ? 0 : this.getLastupdatedtime().hashCode() );
         result = 37 * result + ( getRefunddatetime() == null ? 0 : this.getRefunddatetime().hashCode() );
         result = 37 * result + ( getMotodatetime() == null ? 0 : this.getMotodatetime().hashCode() );
         return result;
   }   


}


