package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgmerchantcategory generated by hbm2java
 */
@Entity
@Table(name = "IPGMERCHANTCATEGORY" )
public class Ipgmerchantcategory implements java.io.Serializable {

    private String mcc;
    private Ipgstatus ipgstatus;
    private String description;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createtime;
    private Set<Ipgriskprofileblockedmcc> ipgriskprofileblockedmccs = new HashSet<Ipgriskprofileblockedmcc>(0);

    public Ipgmerchantcategory() {
    }

    public Ipgmerchantcategory(String mcc, String description) {
        this.mcc = mcc;
        this.description = description;
    }

    public Ipgmerchantcategory(String mcc, Ipgstatus ipgstatus, String description, String lastupdateduser, Date lastupdatedtime, Date createtime, Set<Ipgriskprofileblockedmcc> ipgriskprofileblockedmccs) {
        this.mcc = mcc;
        this.ipgstatus = ipgstatus;
        this.description = description;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createtime = createtime;
        this.ipgriskprofileblockedmccs = ipgriskprofileblockedmccs;
    }

    @Id
    @Column(name = "MCC", unique = true, nullable = false, length = 4)
    public String getMcc() {
        return this.mcc;
    }

    public void setMcc(String mcc) {
        this.mcc = mcc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 256)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATETIME", length = 7)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgmerchantcategory")
    public Set<Ipgriskprofileblockedmcc> getIpgriskprofileblockedmccs() {
        return this.ipgriskprofileblockedmccs;
    }

    public void setIpgriskprofileblockedmccs(Set<Ipgriskprofileblockedmcc> ipgriskprofileblockedmccs) {
        this.ipgriskprofileblockedmccs = ipgriskprofileblockedmccs;
    }
}
