package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgmpiinfo generated by hbm2java
 */
@Entity
@Table(name = "IPGMPIINFO" )
public class Ipgmpiinfo implements java.io.Serializable {

    private long ipgmpiinfoid;
    private String primaryurl;
    private String secounderyurl;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;

    public Ipgmpiinfo() {
    }

    public Ipgmpiinfo(long ipgmpiinfoid) {
        this.ipgmpiinfoid = ipgmpiinfoid;
    }

    public Ipgmpiinfo(long ipgmpiinfoid, String primaryurl, String secounderyurl, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
        this.ipgmpiinfoid = ipgmpiinfoid;
        this.primaryurl = primaryurl;
        this.secounderyurl = secounderyurl;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGMPIINFOID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name = "IPGMPIINFOID", unique = true, nullable = false, precision = 16, scale = 0)
    public long getIpgmpiinfoid() {
        return this.ipgmpiinfoid;
    }

    public void setIpgmpiinfoid(long ipgmpiinfoid) {
        this.ipgmpiinfoid = ipgmpiinfoid;
    }

    @Column(name = "PRIMARYURL")
    public String getPrimaryurl() {
        return this.primaryurl;
    }

    public void setPrimaryurl(String primaryurl) {
        this.primaryurl = primaryurl;
    }

    @Column(name = "SECOUNDERYURL")
    public String getSecounderyurl() {
        return this.secounderyurl;
    }

    public void setSecounderyurl(String secounderyurl) {
        this.secounderyurl = secounderyurl;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
}
