package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgmerchantcurrencyId generated by hbm2java
 */
@Embeddable
public class IpgmerchantcurrencyId  implements java.io.Serializable {


     private String merchantid;
     private String currencycode;

    public IpgmerchantcurrencyId() {
    }

    public IpgmerchantcurrencyId(String merchantid, String currencycode) {
       this.merchantid = merchantid;
       this.currencycode = currencycode;
    }
   

    @Column(name="MERCHANTID", nullable=false, length=15)
    public String getMerchantid() {
        return this.merchantid;
    }
    
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    @Column(name="CURRENCYCODE", nullable=false, length=8)
    public String getCurrencycode() {
        return this.currencycode;
    }
    
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgmerchantcurrencyId) ) return false;
		 IpgmerchantcurrencyId castOther = ( IpgmerchantcurrencyId ) other; 
         
		 return ( (this.getMerchantid()==castOther.getMerchantid()) || ( this.getMerchantid()!=null && castOther.getMerchantid()!=null && this.getMerchantid().equals(castOther.getMerchantid()) ) )
 && ( (this.getCurrencycode()==castOther.getCurrencycode()) || ( this.getCurrencycode()!=null && castOther.getCurrencycode()!=null && this.getCurrencycode().equals(castOther.getCurrencycode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMerchantid() == null ? 0 : this.getMerchantid().hashCode() );
         result = 37 * result + ( getCurrencycode() == null ? 0 : this.getCurrencycode().hashCode() );
         return result;
   }   


}


