package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IpgModulestatus generated by hbm2java
 */
@Entity
@Table(name="IPG_MODULESTATUS")
public class IpgModulestatus  implements java.io.Serializable {


     private IpgModulestatusId id;
     private String tid;
     private String mid;
     private String ipgStatus;
     private String ipgDelay;
     private String mpiStatus;
     private String mpiDelay;
     private String mpiEci;
     private String acs;
     private String acsStatus;
     private String acsDelay;
     private String engineStatus;
     private String engineDelay;
     private String hostDelay;
     private String actionCode;
     private Date lastupdatetime;

    public IpgModulestatus() {
    }

	
    public IpgModulestatus(IpgModulestatusId id) {
        this.id = id;
    }
    public IpgModulestatus(IpgModulestatusId id, String tid, String mid, String ipgStatus, String ipgDelay, String mpiStatus, String mpiDelay, String mpiEci, String acs, String acsStatus, String acsDelay, String engineStatus, String engineDelay, String hostDelay, String actionCode, Date lastupdatetime) {
       this.id = id;
       this.tid = tid;
       this.mid = mid;
       this.ipgStatus = ipgStatus;
       this.ipgDelay = ipgDelay;
       this.mpiStatus = mpiStatus;
       this.mpiDelay = mpiDelay;
       this.mpiEci = mpiEci;
       this.acs = acs;
       this.acsStatus = acsStatus;
       this.acsDelay = acsDelay;
       this.engineStatus = engineStatus;
       this.engineDelay = engineDelay;
       this.hostDelay = hostDelay;
       this.actionCode = actionCode;
       this.lastupdatetime = lastupdatetime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="txnid", column=@Column(name="TXNID", nullable=false, length=20) ), 
        @AttributeOverride(name="txncode", column=@Column(name="TXNCODE", nullable=false, length=2) ) } )
    public IpgModulestatusId getId() {
        return this.id;
    }
    
    public void setId(IpgModulestatusId id) {
        this.id = id;
    }
    
    @Column(name="TID", length=8)
    public String getTid() {
        return this.tid;
    }
    
    public void setTid(String tid) {
        this.tid = tid;
    }
    
    @Column(name="MID", length=15)
    public String getMid() {
        return this.mid;
    }
    
    public void setMid(String mid) {
        this.mid = mid;
    }
    
    @Column(name="IPG_STATUS", length=1)
    public String getIpgStatus() {
        return this.ipgStatus;
    }
    
    public void setIpgStatus(String ipgStatus) {
        this.ipgStatus = ipgStatus;
    }
    
    @Column(name="IPG_DELAY", length=20)
    public String getIpgDelay() {
        return this.ipgDelay;
    }
    
    public void setIpgDelay(String ipgDelay) {
        this.ipgDelay = ipgDelay;
    }
    
    @Column(name="MPI_STATUS", length=1)
    public String getMpiStatus() {
        return this.mpiStatus;
    }
    
    public void setMpiStatus(String mpiStatus) {
        this.mpiStatus = mpiStatus;
    }
    
    @Column(name="MPI_DELAY", length=20)
    public String getMpiDelay() {
        return this.mpiDelay;
    }
    
    public void setMpiDelay(String mpiDelay) {
        this.mpiDelay = mpiDelay;
    }
    
    @Column(name="MPI_ECI", length=2)
    public String getMpiEci() {
        return this.mpiEci;
    }
    
    public void setMpiEci(String mpiEci) {
        this.mpiEci = mpiEci;
    }
    
    @Column(name="ACS", length=20)
    public String getAcs() {
        return this.acs;
    }
    
    public void setAcs(String acs) {
        this.acs = acs;
    }
    
    @Column(name="ACS_STATUS", length=1)
    public String getAcsStatus() {
        return this.acsStatus;
    }
    
    public void setAcsStatus(String acsStatus) {
        this.acsStatus = acsStatus;
    }
    
    @Column(name="ACS_DELAY", length=20)
    public String getAcsDelay() {
        return this.acsDelay;
    }
    
    public void setAcsDelay(String acsDelay) {
        this.acsDelay = acsDelay;
    }
    
    @Column(name="ENGINE_STATUS", length=1)
    public String getEngineStatus() {
        return this.engineStatus;
    }
    
    public void setEngineStatus(String engineStatus) {
        this.engineStatus = engineStatus;
    }
    
    @Column(name="ENGINE_DELAY", length=20)
    public String getEngineDelay() {
        return this.engineDelay;
    }
    
    public void setEngineDelay(String engineDelay) {
        this.engineDelay = engineDelay;
    }
    
    @Column(name="HOST_DELAY", length=20)
    public String getHostDelay() {
        return this.hostDelay;
    }
    
    public void setHostDelay(String hostDelay) {
        this.hostDelay = hostDelay;
    }
    
    @Column(name="ACTION_CODE", length=3)
    public String getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATETIME", length=11)
    public Date getLastupdatetime() {
        return this.lastupdatetime;
    }
    
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }




}


