package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgModulestatusId generated by hbm2java
 */
@Embeddable
public class IpgModulestatusId  implements java.io.Serializable {


     private String txnid;
     private String txncode;

    public IpgModulestatusId() {
    }

    public IpgModulestatusId(String txnid, String txncode) {
       this.txnid = txnid;
       this.txncode = txncode;
    }
   

    @Column(name="TXNID", nullable=false, length=20)
    public String getTxnid() {
        return this.txnid;
    }
    
    public void setTxnid(String txnid) {
        this.txnid = txnid;
    }

    @Column(name="TXNCODE", nullable=false, length=2)
    public String getTxncode() {
        return this.txncode;
    }
    
    public void setTxncode(String txncode) {
        this.txncode = txncode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgModulestatusId) ) return false;
		 IpgModulestatusId castOther = ( IpgModulestatusId ) other; 
         
		 return ( (this.getTxnid()==castOther.getTxnid()) || ( this.getTxnid()!=null && castOther.getTxnid()!=null && this.getTxnid().equals(castOther.getTxnid()) ) )
 && ( (this.getTxncode()==castOther.getTxncode()) || ( this.getTxncode()!=null && castOther.getTxncode()!=null && this.getTxncode().equals(castOther.getTxncode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTxnid() == null ? 0 : this.getTxnid().hashCode() );
         result = 37 * result + ( getTxncode() == null ? 0 : this.getTxncode().hashCode() );
         return result;
   }   


}


