package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgmerchantrule generated by hbm2java
 */
@Entity
@Table(name="IPGMERCHANTRULE"
    
)
public class Ipgmerchantrule  implements java.io.Serializable {


     private IpgmerchantruleId id;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgmerchantrule() {
    }

	
    public Ipgmerchantrule(IpgmerchantruleId id) {
        this.id = id;
    }
    public Ipgmerchantrule(IpgmerchantruleId id, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.id = id;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="merchantid", column=@Column(name="MERCHANTID", nullable=false, length=15) ), 
        @AttributeOverride(name="ruleid", column=@Column(name="RULEID", nullable=false, precision=22, scale=0) ) } )
    public IpgmerchantruleId getId() {
        return this.id;
    }
    
    public void setId(IpgmerchantruleId id) {
        this.id = id;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


