package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgmerchantruleId generated by hbm2java
 */
@Embeddable
public class IpgmerchantruleId  implements java.io.Serializable {


     private String merchantid;
     private BigDecimal ruleid;

    public IpgmerchantruleId() {
    }

    public IpgmerchantruleId(String merchantid, BigDecimal ruleid) {
       this.merchantid = merchantid;
       this.ruleid = ruleid;
    }
   

    @Column(name="MERCHANTID", nullable=false, length=15)
    public String getMerchantid() {
        return this.merchantid;
    }
    
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    @Column(name="RULEID", nullable=false, precision=22, scale=0)
    public BigDecimal getRuleid() {
        return this.ruleid;
    }
    
    public void setRuleid(BigDecimal ruleid) {
        this.ruleid = ruleid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgmerchantruleId) ) return false;
		 IpgmerchantruleId castOther = ( IpgmerchantruleId ) other; 
         
		 return ( (this.getMerchantid()==castOther.getMerchantid()) || ( this.getMerchantid()!=null && castOther.getMerchantid()!=null && this.getMerchantid().equals(castOther.getMerchantid()) ) )
 && ( (this.getRuleid()==castOther.getRuleid()) || ( this.getRuleid()!=null && castOther.getRuleid()!=null && this.getRuleid().equals(castOther.getRuleid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMerchantid() == null ? 0 : this.getMerchantid().hashCode() );
         result = 37 * result + ( getRuleid() == null ? 0 : this.getRuleid().hashCode() );
         return result;
   }   


}


