package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgonusbinrange generated by hbm2java
 */
@Entity
@Table(name="IPGONUSBINRANGE"
    
)
public class Ipgonusbinrange  implements java.io.Serializable {


     private BigDecimal ipgonusbinrangeid;
     private Ipgstatus ipgstatus;
     private String value1;
     private String value2;
     private String remarks;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgonusbinrange() {
    }

	
    public Ipgonusbinrange(BigDecimal ipgonusbinrangeid) {
        this.ipgonusbinrangeid = ipgonusbinrangeid;
    }
    public Ipgonusbinrange(BigDecimal ipgonusbinrangeid, Ipgstatus ipgstatus, String value1, String value2, String remarks, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.ipgonusbinrangeid = ipgonusbinrangeid;
       this.ipgstatus = ipgstatus;
       this.value1 = value1;
       this.value2 = value2;
       this.remarks = remarks;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 
     @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGONUSBINRANGEID_SEQ")
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name="IPGONUSBINRANGEID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIpgonusbinrangeid() {
        return this.ipgonusbinrangeid;
    }
    
    public void setIpgonusbinrangeid(BigDecimal ipgonusbinrangeid) {
        this.ipgonusbinrangeid = ipgonusbinrangeid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUSCODE")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }
    
    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }
    
    @Column(name="VALUE1")
    public String getValue1() {
        return this.value1;
    }
    
    public void setValue1(String value1) {
        this.value1 = value1;
    }
    
    @Column(name="VALUE2")
    public String getValue2() {
        return this.value2;
    }
    
    public void setValue2(String value2) {
        this.value2 = value2;
    }
    
    @Column(name="REMARKS")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


