package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgpage generated by hbm2java
 */
@Entity
@Table(name="IPGPAGE"
    
)
public class Ipgpage  implements java.io.Serializable {


     private String pagecode;
     private Ipgstatus ipgstatus;
     private String description;
     private String url;
     private String root;
     private BigDecimal sortkey;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Ipgsectionpage> ipgsectionpages = new HashSet<Ipgsectionpage>(0);
     private Set<Ipgpagetask> ipgpagetasks = new HashSet<Ipgpagetask>(0);
     private Set<Ipgsystemaudit> ipgsystemaudits = new HashSet<Ipgsystemaudit>(0);

    public Ipgpage() {
    }

	
    public Ipgpage(String pagecode) {
        this.pagecode = pagecode;
    }
    public Ipgpage(String pagecode, Ipgstatus ipgstatus, String description, String url, String root, BigDecimal sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgsectionpage> ipgsectionpages, Set<Ipgpagetask> ipgpagetasks, Set<Ipgsystemaudit> ipgsystemaudits) {
       this.pagecode = pagecode;
       this.ipgstatus = ipgstatus;
       this.description = description;
       this.url = url;
       this.root = root;
       this.sortkey = sortkey;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.ipgsectionpages = ipgsectionpages;
       this.ipgpagetasks = ipgpagetasks;
       this.ipgsystemaudits = ipgsystemaudits;
    }
   
     @Id 
    
    @Column(name="PAGECODE", unique=true, nullable=false, length=16)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUSCODE")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }
    
    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }
    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="URL")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="ROOT", length=16)
    public String getRoot() {
        return this.root;
    }
    
    public void setRoot(String root) {
        this.root = root;
    }
    
    @Column(name="SORTKEY", precision=22, scale=0)
    public BigDecimal getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipgpage")
    public Set<Ipgsectionpage> getIpgsectionpages() {
        return this.ipgsectionpages;
    }
    
    public void setIpgsectionpages(Set<Ipgsectionpage> ipgsectionpages) {
        this.ipgsectionpages = ipgsectionpages;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipgpage")
    public Set<Ipgpagetask> getIpgpagetasks() {
        return this.ipgpagetasks;
    }
    
    public void setIpgpagetasks(Set<Ipgpagetask> ipgpagetasks) {
        this.ipgpagetasks = ipgpagetasks;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipgpage")
    public Set<Ipgsystemaudit> getIpgsystemaudits() {
        return this.ipgsystemaudits;
    }
    
    public void setIpgsystemaudits(Set<Ipgsystemaudit> ipgsystemaudits) {
        this.ipgsystemaudits = ipgsystemaudits;
    }




}


