package com.epic.epay.ipg.util.mapping;
// Generated Jul 31, 2018 10:15:45 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgruleoperator generated by hbm2java
 */
@Entity
@Table(name = "IPGRULEOPERATOR"
)
public class Ipgruleoperator implements java.io.Serializable {

    private IpgruleoperatorId id;
    private Ipgstatus ipgstatus;
    private Ipgrulescope ipgrulescope;
    private Date createdtime;

    public Ipgruleoperator() {
    }

    public Ipgruleoperator(IpgruleoperatorId id, Ipgrulescope ipgrulescope) {
        this.id = id;
        this.ipgrulescope = ipgrulescope;
    }

    public Ipgruleoperator(IpgruleoperatorId id, Ipgstatus ipgstatus, Ipgrulescope ipgrulescope, Date createdtime) {
        this.id = id;
        this.ipgstatus = ipgstatus;
        this.ipgrulescope = ipgrulescope;
        this.createdtime = createdtime;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "ruleoperatorcode", column = @Column(name = "RULEOPERATORCODE", nullable = false, length = 2)),
        @AttributeOverride(name = "rulescopecode", column = @Column(name = "RULESCOPECODE", nullable = false, length = 16))})
    public IpgruleoperatorId getId() {
        return this.id;
    }

    public void setId(IpgruleoperatorId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RULESCOPECODE", nullable = false, insertable = false, updatable = false)
    public Ipgrulescope getIpgrulescope() {
        return this.ipgrulescope;
    }

    public void setIpgrulescope(Ipgrulescope ipgrulescope) {
        this.ipgrulescope = ipgrulescope;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

}
