package com.epic.epay.ipg.util.mapping;
// Generated Jul 31, 2018 10:15:45 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgruletype generated by hbm2java
 */
@Entity
@Table(name="IPGRULETYPE"
)
public class Ipgruletype  implements java.io.Serializable {


     private IpgruletypeId id;
     private Ipgstatus ipgstatus;
     private Ipgrulescope ipgrulescope;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgruletype() {
    }

	
    public Ipgruletype(IpgruletypeId id, Ipgrulescope ipgrulescope) {
        this.id = id;
        this.ipgrulescope = ipgrulescope;
    }
    public Ipgruletype(IpgruletypeId id, Ipgstatus ipgstatus, Ipgrulescope ipgrulescope, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.id = id;
       this.ipgstatus = ipgstatus;
       this.ipgrulescope = ipgrulescope;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ruletypecode", column=@Column(name="RULETYPECODE", nullable=false, length=16) ), 
        @AttributeOverride(name="rulescopecode", column=@Column(name="RULESCOPECODE", nullable=false, length=16) ) } )
    public IpgruletypeId getId() {
        return this.id;
    }
    
    public void setId(IpgruletypeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }
    
    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RULESCOPECODE", nullable=false, insertable=false, updatable=false)
    public Ipgrulescope getIpgrulescope() {
        return this.ipgrulescope;
    }
    
    public void setIpgrulescope(Ipgrulescope ipgrulescope) {
        this.ipgrulescope = ipgrulescope;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}




