package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgriskprofile generated by hbm2java
 */
@Entity
@Table(name = "IPGRISKPROFILE" )
public class Ipgriskprofile implements java.io.Serializable {

    private String riskprofilecode;
    private Ipgstatus ipgstatus;
    private String profiletype;
    private String description;
    private BigDecimal maximumsingletxnlimit;
    private Short maximumtxncount;
    private BigDecimal minimumsingletxnlimit;
    private BigDecimal maximumtotaltxnamount;
    private Byte maximumpasswordcount;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgmerchant> ipgmerchants = new HashSet<Ipgmerchant>(0);
    private Set<Ipgriskprofileblockedcountry> ipgriskprofileblockedcountries = new HashSet<Ipgriskprofileblockedcountry>(0);
    private Set<Ipgriskprofileblockedcurrency> ipgriskprofileblockedcurrencies = new HashSet<Ipgriskprofileblockedcurrency>(0);
    private Set<Ipgriskprofileblockedbin> ipgriskprofileblockedbins = new HashSet<Ipgriskprofileblockedbin>(0);
    private Set<Ipgriskprofileblockedmcc> ipgriskprofileblockedmccs = new HashSet<Ipgriskprofileblockedmcc>(0);
    private Set<Ipgheadmerchant> ipgheadmerchants = new HashSet<Ipgheadmerchant>(0);

    public Ipgriskprofile() {
    }

    public Ipgriskprofile(String riskprofilecode) {
        this.riskprofilecode = riskprofilecode;
    }

    public Ipgriskprofile(String riskprofilecode, Set<Ipgheadmerchant> ipgheadmerchants, Ipgstatus ipgstatus, String profiletype, String description, BigDecimal maximumsingletxnlimit, Short maximumtxncount, BigDecimal minimumsingletxnlimit, BigDecimal maximumtotaltxnamount, Byte maximumpasswordcount, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgmerchant> ipgmerchants, Set<Ipgriskprofileblockedcountry> ipgriskprofileblockedcountries, Set<Ipgriskprofileblockedcurrency> ipgriskprofileblockedcurrencies, Set<Ipgriskprofileblockedbin> ipgriskprofileblockedbins, Set<Ipgriskprofileblockedmcc> ipgriskprofileblockedmccs) {
        this.riskprofilecode = riskprofilecode;
        this.ipgstatus = ipgstatus;
        this.profiletype = profiletype;
        this.description = description;
        this.maximumsingletxnlimit = maximumsingletxnlimit;
        this.maximumtxncount = maximumtxncount;
        this.minimumsingletxnlimit = minimumsingletxnlimit;
        this.maximumtotaltxnamount = maximumtotaltxnamount;
        this.maximumpasswordcount = maximumpasswordcount;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgmerchants = ipgmerchants;
        this.ipgriskprofileblockedcountries = ipgriskprofileblockedcountries;
        this.ipgriskprofileblockedcurrencies = ipgriskprofileblockedcurrencies;
        this.ipgriskprofileblockedbins = ipgriskprofileblockedbins;
        this.ipgriskprofileblockedmccs = ipgriskprofileblockedmccs;
        this.ipgheadmerchants = ipgheadmerchants;
    }

    @Id
    @Column(name = "RISKPROFILECODE", unique = true, nullable = false, length = 8)
    public String getRiskprofilecode() {
        return this.riskprofilecode;
    }

    public void setRiskprofilecode(String riskprofilecode) {
        this.riskprofilecode = riskprofilecode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    @Column(name = "PROFILETYPE", length = 16)
    public String getProfiletype() {
        return this.profiletype;
    }

    public void setProfiletype(String profiletype) {
        this.profiletype = profiletype;
    }

    @Column(name = "DESCRIPTION", length = 64)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "MAXIMUMSINGLETXNLIMIT", precision = 10)
    public BigDecimal getMaximumsingletxnlimit() {
        return this.maximumsingletxnlimit;
    }

    public void setMaximumsingletxnlimit(BigDecimal maximumsingletxnlimit) {
        this.maximumsingletxnlimit = maximumsingletxnlimit;
    }

    @Column(name = "MAXIMUMTXNCOUNT", precision = 4, scale = 0)
    public Short getMaximumtxncount() {
        return this.maximumtxncount;
    }

    public void setMaximumtxncount(Short maximumtxncount) {
        this.maximumtxncount = maximumtxncount;
    }

    @Column(name = "MINIMUMSINGLETXNLIMIT", precision = 10)
    public BigDecimal getMinimumsingletxnlimit() {
        return this.minimumsingletxnlimit;
    }

    public void setMinimumsingletxnlimit(BigDecimal minimumsingletxnlimit) {
        this.minimumsingletxnlimit = minimumsingletxnlimit;
    }

    @Column(name = "MAXIMUMTOTALTXNAMOUNT", precision = 10)
    public BigDecimal getMaximumtotaltxnamount() {
        return this.maximumtotaltxnamount;
    }

    public void setMaximumtotaltxnamount(BigDecimal maximumtotaltxnamount) {
        this.maximumtotaltxnamount = maximumtotaltxnamount;
    }

    @Column(name = "MAXIMUMPASSWORDCOUNT", precision = 2, scale = 0)
    public Byte getMaximumpasswordcount() {
        return this.maximumpasswordcount;
    }

    public void setMaximumpasswordcount(Byte maximumpasswordcount) {
        this.maximumpasswordcount = maximumpasswordcount;
    }

    @Column(name = "LASTUPDATEDUSER", length = 32)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgriskprofile")
    public Set<Ipgmerchant> getIpgmerchants() {
        return this.ipgmerchants;
    }

    public void setIpgmerchants(Set<Ipgmerchant> ipgmerchants) {
        this.ipgmerchants = ipgmerchants;
    }

    @OneToMany(  fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "ipgriskprofile")
    public Set<Ipgriskprofileblockedcountry> getIpgriskprofileblockedcountries() {
        return this.ipgriskprofileblockedcountries;
    }

    public void setIpgriskprofileblockedcountries(Set<Ipgriskprofileblockedcountry> ipgriskprofileblockedcountries) {
        this.ipgriskprofileblockedcountries = ipgriskprofileblockedcountries;
    }

    @OneToMany(  fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "ipgriskprofile")
    public Set<Ipgriskprofileblockedcurrency> getIpgriskprofileblockedcurrencies() {
        return this.ipgriskprofileblockedcurrencies;
    }

    public void setIpgriskprofileblockedcurrencies(Set<Ipgriskprofileblockedcurrency> ipgriskprofileblockedcurrencies) {
        this.ipgriskprofileblockedcurrencies = ipgriskprofileblockedcurrencies;
    }

    @OneToMany(  fetch = FetchType.LAZY ,cascade = CascadeType.ALL, mappedBy = "ipgriskprofile")
    public Set<Ipgriskprofileblockedbin> getIpgriskprofileblockedbins() {
        return this.ipgriskprofileblockedbins;
    }

    public void setIpgriskprofileblockedbins(Set<Ipgriskprofileblockedbin> ipgriskprofileblockedbins) {
        this.ipgriskprofileblockedbins = ipgriskprofileblockedbins;
    }

    @OneToMany(  fetch = FetchType.LAZY ,cascade = CascadeType.ALL, mappedBy = "ipgriskprofile")
    public Set<Ipgriskprofileblockedmcc> getIpgriskprofileblockedmccs() {
        return this.ipgriskprofileblockedmccs;
    }

    public void setIpgriskprofileblockedmccs(Set<Ipgriskprofileblockedmcc> ipgriskprofileblockedmccs) {
        this.ipgriskprofileblockedmccs = ipgriskprofileblockedmccs;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgriskprofile")
    public Set<Ipgheadmerchant> getIpgheadmerchants() {
        return this.ipgheadmerchants;
    }

    public void setIpgheadmerchants(Set<Ipgheadmerchant> ipgheadmerchants) {
        this.ipgheadmerchants = ipgheadmerchants;
    }
}
