package com.epic.epay.ipg.util.mapping;
// Generated Nov 8, 2013 10:12:37 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgriskprofileblockedmcc generated by hbm2java
 */
@Entity
@Table(name="IPGRISKPROFILEBLOCKEDMCC"
    
)
public class Ipgriskprofileblockedmcc  implements java.io.Serializable {


     private IpgriskprofileblockedmccId id;
     private Ipgriskprofile ipgriskprofile;
     private Ipgmerchantcategory ipgmerchantcategory;
     private Date createdtime;

    public Ipgriskprofileblockedmcc() {
    }

	
    public Ipgriskprofileblockedmcc(IpgriskprofileblockedmccId id, Ipgriskprofile ipgriskprofile, Ipgmerchantcategory ipgmerchantcategory) {
        this.id = id;
        this.ipgriskprofile = ipgriskprofile;
        this.ipgmerchantcategory = ipgmerchantcategory;
    }
    public Ipgriskprofileblockedmcc(IpgriskprofileblockedmccId id, Ipgriskprofile ipgriskprofile, Ipgmerchantcategory ipgmerchantcategory, Date createdtime) {
       this.id = id;
       this.ipgriskprofile = ipgriskprofile;
       this.ipgmerchantcategory = ipgmerchantcategory;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="mcccode", column=@Column(name="MCCCODE", nullable=false, length=4) ), 
        @AttributeOverride(name="riskprofilecode", column=@Column(name="RISKPROFILECODE", nullable=false, length=8) ) } )
    public IpgriskprofileblockedmccId getId() {
        return this.id;
    }
    
    public void setId(IpgriskprofileblockedmccId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RISKPROFILECODE", nullable=false, insertable=false, updatable=false)
    public Ipgriskprofile getIpgriskprofile() {
        return this.ipgriskprofile;
    }
    
    public void setIpgriskprofile(Ipgriskprofile ipgriskprofile) {
        this.ipgriskprofile = ipgriskprofile;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MCCCODE", nullable=false, insertable=false, updatable=false)
    public Ipgmerchantcategory getIpgmerchantcategory() {
        return this.ipgmerchantcategory;
    }
    
    public void setIpgmerchantcategory(Ipgmerchantcategory ipgmerchantcategory) {
        this.ipgmerchantcategory = ipgmerchantcategory;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


