package com.epic.epay.ipg.util.mapping;

// Generated Aug 8, 2018 5:36:32 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ipgresponsecodes generated by hbm2java
 */
@Entity
@Table(name="IPGRESPONSECODES"
)
public class Ipgresponsecodes  implements java.io.Serializable {


     private String code;
     private String description;

    public Ipgresponsecodes() {
    }

	
    public Ipgresponsecodes(String code) {
        this.code = code;
    }
    public Ipgresponsecodes(String code, String description) {
       this.code = code;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}