package com.epic.epay.ipg.util.mapping;
// Generated Nov 8, 2013 9:17:09 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgriskprofileblockedcountryId generated by hbm2java
 */
@Embeddable
public class IpgriskprofileblockedcountryId  implements java.io.Serializable {


     private String riskprofilecode;
     private String countrycode;

    public IpgriskprofileblockedcountryId() {
    }

    public IpgriskprofileblockedcountryId(String riskprofilecode, String countrycode) {
       this.riskprofilecode = riskprofilecode;
       this.countrycode = countrycode;
    }
   

    @Column(name="RISKPROFILECODE", nullable=false, length=8)
    public String getRiskprofilecode() {
        return this.riskprofilecode;
    }
    
    public void setRiskprofilecode(String riskprofilecode) {
        this.riskprofilecode = riskprofilecode;
    }

    @Column(name="COUNTRYCODE", nullable=false, length=8)
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgriskprofileblockedcountryId) ) return false;
		 IpgriskprofileblockedcountryId castOther = ( IpgriskprofileblockedcountryId ) other; 
         
		 return ( (this.getRiskprofilecode()==castOther.getRiskprofilecode()) || ( this.getRiskprofilecode()!=null && castOther.getRiskprofilecode()!=null && this.getRiskprofilecode().equals(castOther.getRiskprofilecode()) ) )
 && ( (this.getCountrycode()==castOther.getCountrycode()) || ( this.getCountrycode()!=null && castOther.getCountrycode()!=null && this.getCountrycode().equals(castOther.getCountrycode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRiskprofilecode() == null ? 0 : this.getRiskprofilecode().hashCode() );
         result = 37 * result + ( getCountrycode() == null ? 0 : this.getCountrycode().hashCode() );
         return result;
   }   


}


