package com.epic.epay.ipg.util.mapping;
// Generated Nov 8, 2013 10:12:37 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgriskprofileblockedmccId generated by hbm2java
 */
@Embeddable
public class IpgriskprofileblockedmccId  implements java.io.Serializable {


     private String mcccode;
     private String riskprofilecode;

    public IpgriskprofileblockedmccId() {
    }

    public IpgriskprofileblockedmccId(String mcccode, String riskprofilecode) {
       this.mcccode = mcccode;
       this.riskprofilecode = riskprofilecode;
    }
   

    @Column(name="MCCCODE", nullable=false, length=4)
    public String getMcccode() {
        return this.mcccode;
    }
    
    public void setMcccode(String mcccode) {
        this.mcccode = mcccode;
    }

    @Column(name="RISKPROFILECODE", nullable=false, length=8)
    public String getRiskprofilecode() {
        return this.riskprofilecode;
    }
    
    public void setRiskprofilecode(String riskprofilecode) {
        this.riskprofilecode = riskprofilecode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgriskprofileblockedmccId) ) return false;
		 IpgriskprofileblockedmccId castOther = ( IpgriskprofileblockedmccId ) other; 
         
		 return ( (this.getMcccode()==castOther.getMcccode()) || ( this.getMcccode()!=null && castOther.getMcccode()!=null && this.getMcccode().equals(castOther.getMcccode()) ) )
 && ( (this.getRiskprofilecode()==castOther.getRiskprofilecode()) || ( this.getRiskprofilecode()!=null && castOther.getRiskprofilecode()!=null && this.getRiskprofilecode().equals(castOther.getRiskprofilecode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMcccode() == null ? 0 : this.getMcccode().hashCode() );
         result = 37 * result + ( getRiskprofilecode() == null ? 0 : this.getRiskprofilecode().hashCode() );
         return result;
   }   


}


