package com.epic.epay.ipg.util.mapping;
// Generated Jul 31, 2018 10:15:45 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgruletypeId generated by hbm2java
 */
@Embeddable
public class IpgruletypeId  implements java.io.Serializable {


     private String ruletypecode;
     private String rulescopecode;

    public IpgruletypeId() {
    }

    public IpgruletypeId(String ruletypecode, String rulescopecode) {
       this.ruletypecode = ruletypecode;
       this.rulescopecode = rulescopecode;
    }
   


    @Column(name="RULETYPECODE", nullable=false, length=16)
    public String getRuletypecode() {
        return this.ruletypecode;
    }
    
    public void setRuletypecode(String ruletypecode) {
        this.ruletypecode = ruletypecode;
    }


    @Column(name="RULESCOPECODE", nullable=false, length=16)
    public String getRulescopecode() {
        return this.rulescopecode;
    }
    
    public void setRulescopecode(String rulescopecode) {
        this.rulescopecode = rulescopecode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgruletypeId) ) return false;
		 IpgruletypeId castOther = ( IpgruletypeId ) other; 
         
		 return ( (this.getRuletypecode()==castOther.getRuletypecode()) || ( this.getRuletypecode()!=null && castOther.getRuletypecode()!=null && this.getRuletypecode().equals(castOther.getRuletypecode()) ) )
 && ( (this.getRulescopecode()==castOther.getRulescopecode()) || ( this.getRulescopecode()!=null && castOther.getRulescopecode()!=null && this.getRulescopecode().equals(castOther.getRulescopecode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRuletypecode() == null ? 0 : this.getRuletypecode().hashCode() );
         result = 37 * result + ( getRulescopecode() == null ? 0 : this.getRulescopecode().hashCode() );
         return result;
   }   


}
