package com.epic.epay.ipg.util.mapping;
// Generated Nov 8, 2013 9:17:09 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgriskprofileblockedbin generated by hbm2java
 */
@Entity
@Table(name="IPGRISKPROFILEBLOCKEDBIN"
    
)
public class Ipgriskprofileblockedbin  implements java.io.Serializable {


     private IpgriskprofileblockedbinId id;
     private Ipgbin ipgbin;
     private Ipgriskprofile ipgriskprofile;
     private Date createdtime;

    public Ipgriskprofileblockedbin() {
    }

	
    public Ipgriskprofileblockedbin(IpgriskprofileblockedbinId id, Ipgbin ipgbin, Ipgriskprofile ipgriskprofile) {
        this.id = id;
        this.ipgbin = ipgbin;
        this.ipgriskprofile = ipgriskprofile;
    }
    public Ipgriskprofileblockedbin(IpgriskprofileblockedbinId id, Ipgbin ipgbin, Ipgriskprofile ipgriskprofile, Date createdtime) {
       this.id = id;
       this.ipgbin = ipgbin;
       this.ipgriskprofile = ipgriskprofile;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="bin", column=@Column(name="BIN", nullable=false, length=6) ), 
        @AttributeOverride(name="riskprofilecode", column=@Column(name="RISKPROFILECODE", nullable=false, length=8) ) } )
    public IpgriskprofileblockedbinId getId() {
        return this.id;
    }
    
    public void setId(IpgriskprofileblockedbinId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIN", nullable=false, insertable=false, updatable=false)
    public Ipgbin getIpgbin() {
        return this.ipgbin;
    }
    
    public void setIpgbin(Ipgbin ipgbin) {
        this.ipgbin = ipgbin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RISKPROFILECODE", nullable=false, insertable=false, updatable=false)
    public Ipgriskprofile getIpgriskprofile() {
        return this.ipgriskprofile;
    }
    
    public void setIpgriskprofile(Ipgriskprofile ipgriskprofile) {
        this.ipgriskprofile = ipgriskprofile;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


