package com.epic.epay.ipg.util.mapping;
// Generated Nov 8, 2013 9:17:09 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgriskprofileblockedbinId generated by hbm2java
 */
@Embeddable
public class IpgriskprofileblockedbinId  implements java.io.Serializable {


     private String bin;
     private String riskprofilecode;

    public IpgriskprofileblockedbinId() {
    }

    public IpgriskprofileblockedbinId(String bin, String riskprofilecode) {
       this.bin = bin;
       this.riskprofilecode = riskprofilecode;
    }
   

    @Column(name="BIN", nullable=false, length=6)
    public String getBin() {
        return this.bin;
    }
    
    public void setBin(String bin) {
        this.bin = bin;
    }

    @Column(name="RISKPROFILECODE", nullable=false, length=8)
    public String getRiskprofilecode() {
        return this.riskprofilecode;
    }
    
    public void setRiskprofilecode(String riskprofilecode) {
        this.riskprofilecode = riskprofilecode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgriskprofileblockedbinId) ) return false;
		 IpgriskprofileblockedbinId castOther = ( IpgriskprofileblockedbinId ) other; 
         
		 return ( (this.getBin()==castOther.getBin()) || ( this.getBin()!=null && castOther.getBin()!=null && this.getBin().equals(castOther.getBin()) ) )
 && ( (this.getRiskprofilecode()==castOther.getRiskprofilecode()) || ( this.getRiskprofilecode()!=null && castOther.getRiskprofilecode()!=null && this.getRiskprofilecode().equals(castOther.getRiskprofilecode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBin() == null ? 0 : this.getBin().hashCode() );
         result = 37 * result + ( getRiskprofilecode() == null ? 0 : this.getRiskprofilecode().hashCode() );
         return result;
   }   


}


