package com.epic.epay.ipg.util.mapping;
// Generated Jul 31, 2018 10:15:45 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgruleoperatorId generated by hbm2java
 */
@Embeddable
public class IpgruleoperatorId  implements java.io.Serializable {


     private String ruleoperatorcode;
     private String rulescopecode;

    public IpgruleoperatorId() {
    }

    public IpgruleoperatorId(String ruleoperatorcode, String rulescopecode) {
       this.ruleoperatorcode = ruleoperatorcode;
       this.rulescopecode = rulescopecode;
    }
   


    @Column(name="RULEOPERATORCODE", nullable=false, length=2)
    public String getRuleoperatorcode() {
        return this.ruleoperatorcode;
    }
    
    public void setRuleoperatorcode(String ruleoperatorcode) {
        this.ruleoperatorcode = ruleoperatorcode;
    }


    @Column(name="RULESCOPECODE", nullable=false, length=16)
    public String getRulescopecode() {
        return this.rulescopecode;
    }
    
    public void setRulescopecode(String rulescopecode) {
        this.rulescopecode = rulescopecode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgruleoperatorId) ) return false;
		 IpgruleoperatorId castOther = ( IpgruleoperatorId ) other; 
         
		 return ( (this.getRuleoperatorcode()==castOther.getRuleoperatorcode()) || ( this.getRuleoperatorcode()!=null && castOther.getRuleoperatorcode()!=null && this.getRuleoperatorcode().equals(castOther.getRuleoperatorcode()) ) )
 && ( (this.getRulescopecode()==castOther.getRulescopecode()) || ( this.getRulescopecode()!=null && castOther.getRulescopecode()!=null && this.getRulescopecode().equals(castOther.getRulescopecode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRuleoperatorcode() == null ? 0 : this.getRuleoperatorcode().hashCode() );
         result = 37 * result + ( getRulescopecode() == null ? 0 : this.getRulescopecode().hashCode() );
         return result;
   }   


}
