package com.epic.epay.ipg.util.mapping;
// Generated Jul 31, 2018 10:15:45 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgrulescope generated by hbm2java
 */
@Entity
@Table(name="IPGRULESCOPE"
)
public class Ipgrulescope  implements java.io.Serializable {


     private String rulescopecode;
     private Ipgstatus ipgstatus;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgrulescope() {
    }

	
    public Ipgrulescope(String rulescopecode) {
        this.rulescopecode = rulescopecode;
    }
    public Ipgrulescope(String rulescopecode, Ipgstatus ipgstatus, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.rulescopecode = rulescopecode;
       this.ipgstatus = ipgstatus;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 

    
    @Column(name="RULESCOPECODE", unique=true, nullable=false, length=16)
    public String getRulescopecode() {
        return this.rulescopecode;
    }
    
    public void setRulescopecode(String rulescopecode) {
        this.rulescopecode = rulescopecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }
    
    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}





