package com.epic.epay.ipg.util.mapping;
// Generated Nov 8, 2013 9:17:09 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgriskprofileblockedcountry generated by hbm2java
 */
@Entity
@Table(name="IPGRISKPROFILEBLOCKEDCOUNTRY"
    
)
public class Ipgriskprofileblockedcountry  implements java.io.Serializable {


     private IpgriskprofileblockedcountryId id;
     private Ipgcountry ipgcountry;
     private Ipgriskprofile ipgriskprofile;
     private Date createdtime;

    public Ipgriskprofileblockedcountry() {
    }

	
    public Ipgriskprofileblockedcountry(IpgriskprofileblockedcountryId id, Ipgcountry ipgcountry, Ipgriskprofile ipgriskprofile) {
        this.id = id;
        this.ipgcountry = ipgcountry;
        this.ipgriskprofile = ipgriskprofile;
    }
    public Ipgriskprofileblockedcountry(IpgriskprofileblockedcountryId id, Ipgcountry ipgcountry, Ipgriskprofile ipgriskprofile, Date createdtime) {
       this.id = id;
       this.ipgcountry = ipgcountry;
       this.ipgriskprofile = ipgriskprofile;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="riskprofilecode", column=@Column(name="RISKPROFILECODE", nullable=false, length=8) ), 
        @AttributeOverride(name="countrycode", column=@Column(name="COUNTRYCODE", nullable=false, length=8) ) } )
    public IpgriskprofileblockedcountryId getId() {
        return this.id;
    }
    
    public void setId(IpgriskprofileblockedcountryId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COUNTRYCODE", nullable=false, insertable=false, updatable=false)
    public Ipgcountry getIpgcountry() {
        return this.ipgcountry;
    }
    
    public void setIpgcountry(Ipgcountry ipgcountry) {
        this.ipgcountry = ipgcountry;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RISKPROFILECODE", nullable=false, insertable=false, updatable=false)
    public Ipgriskprofile getIpgriskprofile() {
        return this.ipgriskprofile;
    }
    
    public void setIpgriskprofile(Ipgriskprofile ipgriskprofile) {
        this.ipgriskprofile = ipgriskprofile;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


