package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgservicechargetype generated by hbm2java
 */
@Entity
@Table(name="IPGSERVICECHARGETYPE"
    
)
public class Ipgservicechargetype  implements java.io.Serializable {


     private String servicechargetypecode;
     private String description;
     private BigDecimal sortkey;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Ipgservicecharge> ipgservicecharges = new HashSet<Ipgservicecharge>(0);

    public Ipgservicechargetype() {
    }

	
    public Ipgservicechargetype(String servicechargetypecode) {
        this.servicechargetypecode = servicechargetypecode;
    }
    public Ipgservicechargetype(String servicechargetypecode, String description, BigDecimal sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgservicecharge> ipgservicecharges) {
       this.servicechargetypecode = servicechargetypecode;
       this.description = description;
       this.sortkey = sortkey;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.ipgservicecharges = ipgservicecharges;
    }
   
     @Id 
    
    @Column(name="SERVICECHARGETYPECODE", unique=true, nullable=false, length=16)
    public String getServicechargetypecode() {
        return this.servicechargetypecode;
    }
    
    public void setServicechargetypecode(String servicechargetypecode) {
        this.servicechargetypecode = servicechargetypecode;
    }
    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SORTKEY", precision=22, scale=0)
    public BigDecimal getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipgservicechargetype")
    public Set<Ipgservicecharge> getIpgservicecharges() {
        return this.ipgservicecharges;
    }
    
    public void setIpgservicecharges(Set<Ipgservicecharge> ipgservicecharges) {
        this.ipgservicecharges = ipgservicecharges;
    }




}


