package com.epic.epay.ipg.util.mapping;
// Generated Oct 13, 2014 9:41:33 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgsettlementfile generated by hbm2java
 */
@Entity
@Table(name = "IPGSETTLEMENTFILE")
public class Ipgsettlementfile implements java.io.Serializable {

    private String fileid;
    private Ipgstatus ipgstatus;
    private String sequenceno;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgbatch> ipgbatchs = new HashSet<Ipgbatch>(0);

    public Ipgsettlementfile() {
    }

    public Ipgsettlementfile(String fileid) {
        this.fileid = fileid;
    }

    public Ipgsettlementfile(String fileid, Ipgstatus ipgstatus, String sequenceno, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgbatch> ipgbatchs) {
        this.fileid = fileid;
        this.ipgstatus = ipgstatus;
        this.sequenceno = sequenceno;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgbatchs = ipgbatchs;
    }

    @Id
    @Column(name = "FILEID", unique = true, nullable = false, length = 20)
    public String getFileid() {
        return this.fileid;
    }

    public void setFileid(String fileid) {
        this.fileid = fileid;
    }

    @Column(name = "SEQUENCENO", length = 128)
    public String getSequenceno() {
        return this.sequenceno;
    }

    public void setSequenceno(String sequenceno) {
        this.sequenceno = sequenceno;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ipgsettlementfile")
    public Set<Ipgbatch> getIpgbatchs() {
        return this.ipgbatchs;
    }

    public void setIpgbatchs(Set<Ipgbatch> ipgbatchs) {
        this.ipgbatchs = ipgbatchs;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }
}
