package com.epic.epay.ipg.util.mapping;

// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ipgsystemuser generated by hbm2java
 */
@Entity
@Table(name = "IPGSYSTEMUSER" , uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class Ipgsystemuser implements java.io.Serializable {

	private BigDecimal systemuserid;
	private Ipguserrole ipguserroleByDualauthuserrole;
	private Ipgstatus ipgstatus;
	private Ipguserrole ipguserroleByUserrolecode;
	private String password;
	private String username;
	private String merchantid;
	private String empid;
	private Date expirydate;
	private String city;
	private String mobile;
	private String telno;
	private String fax;
	private String sessionid;
	private String lastupdateduser;
	private Date lastupdatedtime;
	private Date createdtime;
	private String fullname;
	private BigDecimal addressid;
	private Integer pincount;
	private String address1;
	private String address2;
	private String email;

	public Ipgsystemuser() {
	}

	public Ipgsystemuser(BigDecimal systemuserid) {
		this.systemuserid = systemuserid;
	}

	public Ipgsystemuser(BigDecimal systemuserid,
			Ipguserrole ipguserroleByDualauthuserrole, Ipgstatus ipgstatus,
			Ipguserrole ipguserroleByUserrolecode, String password,
			String username, String merchantid, String empid, Date expirydate,
			String city, String mobile, String telno, String fax,
			String sessionid, String lastupdateduser, Date lastupdatedtime,
			Date createdtime, String fullname, BigDecimal addressid,
			Integer pincount, String address1, String address2, String email) {
		this.systemuserid = systemuserid;
		this.ipguserroleByDualauthuserrole = ipguserroleByDualauthuserrole;
		this.ipgstatus = ipgstatus;
		this.ipguserroleByUserrolecode = ipguserroleByUserrolecode;
		this.password = password;
		this.username = username;
		this.merchantid = merchantid;
		this.empid = empid;
		this.expirydate = expirydate;
		this.city = city;
		this.mobile = mobile;
		this.telno = telno;
		this.fax = fax;
		this.sessionid = sessionid;
		this.lastupdateduser = lastupdateduser;
		this.lastupdatedtime = lastupdatedtime;
		this.createdtime = createdtime;
		this.fullname = fullname;
		this.addressid = addressid;
		this.pincount = pincount;
		this.address1 = address1;
		this.address2 = address2;
		this.email = email;
	}

	@Id
	@SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGSYSTEMUSERID_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
	@Column(name = "SYSTEMUSERID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSystemuserid() {
		return this.systemuserid;
	}

	public void setSystemuserid(BigDecimal systemuserid) {
		this.systemuserid = systemuserid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DUALAUTHUSERROLE")
	public Ipguserrole getIpguserroleByDualauthuserrole() {
		return this.ipguserroleByDualauthuserrole;
	}

	public void setIpguserroleByDualauthuserrole(
			Ipguserrole ipguserroleByDualauthuserrole) {
		this.ipguserroleByDualauthuserrole = ipguserroleByDualauthuserrole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUCODE")
	public Ipgstatus getIpgstatus() {
		return this.ipgstatus;
	}

	public void setIpgstatus(Ipgstatus ipgstatus) {
		this.ipgstatus = ipgstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERROLECODE")
	public Ipguserrole getIpguserroleByUserrolecode() {
		return this.ipguserroleByUserrolecode;
	}

	public void setIpguserroleByUserrolecode(
			Ipguserrole ipguserroleByUserrolecode) {
		this.ipguserroleByUserrolecode = ipguserroleByUserrolecode;
	}

	@Column(name = "PASSWORD", length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USERNAME", unique = true, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "MERCHANTID", length = 15)
	public String getMerchantid() {
		return this.merchantid;
	}

	public void setMerchantid(String merchantid) {
		this.merchantid = merchantid;
	}

	@Column(name = "EMPID", length = 64)
	public String getEmpid() {
		return this.empid;
	}

	public void setEmpid(String empid) {
		this.empid = empid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRYDATE", length = 7)
	public Date getExpirydate() {
		return this.expirydate;
	}

	public void setExpirydate(Date expirydate) {
		this.expirydate = expirydate;
	}

	@Column(name = "CITY", length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "MOBILE", length = 16)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "TELNO", length = 16)
	public String getTelno() {
		return this.telno;
	}

	public void setTelno(String telno) {
		this.telno = telno;
	}

	@Column(name = "FAX", length = 16)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "SESSIONID")
	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	@Column(name = "LASTUPDATEDUSER")
	public String getLastupdateduser() {
		return this.lastupdateduser;
	}

	public void setLastupdateduser(String lastupdateduser) {
		this.lastupdateduser = lastupdateduser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATEDTIME", length = 7)
	public Date getLastupdatedtime() {
		return this.lastupdatedtime;
	}

	public void setLastupdatedtime(Date lastupdatedtime) {
		this.lastupdatedtime = lastupdatedtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDTIME", length = 7)
	public Date getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	@Column(name = "FULLNAME")
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "ADDRESSID", precision = 22, scale = 0)
	public BigDecimal getAddressid() {
		return this.addressid;
	}

	public void setAddressid(BigDecimal addressid) {
		this.addressid = addressid;
	}

	@Column(name = "PINCOUNT")
	public Integer getPincount() {
		return this.pincount;
	}

	public void setPincount(Integer pincount) {
		this.pincount = pincount;
	}

	@Column(name = "ADDRESS1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
