package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgsectionpage generated by hbm2java
 */
@Entity
@Table(name="IPGSECTIONPAGE"
    
)
public class Ipgsectionpage  implements java.io.Serializable {


     private IpgsectionpageId id;
     private Ipgsection ipgsection;
     private Ipgpage ipgpage;
     private Ipguserrole ipguserrole;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgsectionpage() {
    	
    }
    
    public Ipgsectionpage(IpgsectionpageId id, Ipgsection ipgsection, Ipgpage ipgpage) {
        this.id = id;
        this.ipgsection = ipgsection;
        this.ipgpage = ipgpage;
    }
	
    public Ipgsectionpage(IpgsectionpageId id, Ipgsection ipgsection, Ipgpage ipgpage, Ipguserrole ipguserrole) {
        this.id = id;
        this.ipgsection = ipgsection;
        this.ipgpage = ipgpage;
        this.ipguserrole = ipguserrole;
    }
    public Ipgsectionpage(IpgsectionpageId id, Ipgsection ipgsection, Ipgpage ipgpage, Ipguserrole ipguserrole, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.id = id;
       this.ipgsection = ipgsection;
       this.ipgpage = ipgpage;
       this.ipguserrole = ipguserrole;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userrolecode", column=@Column(name="USERROLECODE", nullable=false, length=16) ), 
        @AttributeOverride(name="sectioncode", column=@Column(name="SECTIONCODE", nullable=false, length=16) ), 
        @AttributeOverride(name="pagecode", column=@Column(name="PAGECODE", nullable=false, length=16) ) } )
    public IpgsectionpageId getId() {
        return this.id;
    }
    
    public void setId(IpgsectionpageId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTIONCODE", nullable=false, insertable=false, updatable=false)
    public Ipgsection getIpgsection() {
        return this.ipgsection;
    }
    
    public void setIpgsection(Ipgsection ipgsection) {
        this.ipgsection = ipgsection;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGECODE", nullable=false, insertable=false, updatable=false)
    public Ipgpage getIpgpage() {
        return this.ipgpage;
    }
    
    public void setIpgpage(Ipgpage ipgpage) {
        this.ipgpage = ipgpage;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLECODE", nullable=false, insertable=false, updatable=false)
    public Ipguserrole getIpguserrole() {
        return this.ipguserrole;
    }
    
    public void setIpguserrole(Ipguserrole ipguserrole) {
        this.ipguserrole = ipguserrole;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


