package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgstatus generated by hbm2java
 */
@Entity
@Table(name = "IPGSTATUS")
public class Ipgstatus implements java.io.Serializable {

    private String statuscode;
    private Ipgstatuscategory ipgstatuscategory;
    private String description;
    private BigDecimal sortkey;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgheadmerchant> ipgheadmerchantsForStatuscode = new HashSet<Ipgheadmerchant>(0);
    private Set<Ipgheadmerchant> ipgheadmerchantsForAuthenticationrequied = new HashSet<Ipgheadmerchant>(0);
    private Set<Ipgheadmerchant> ipgheadmerchantsForTransactioninitaiatedstatus = new HashSet<Ipgheadmerchant>(0);
    private Set<Ipgtransactionhistory> ipgtransactionhistories = new HashSet<Ipgtransactionhistory>(0);
    private Set<Ipgccbafile> ipgccbafiles = new HashSet<Ipgccbafile>(0);
    private Set<Ipgmerchnatterminal> ipgmerchnatterminals = new HashSet<Ipgmerchnatterminal>(0);
    private Set<Ipgmerchantcategory> ipgmerchantcategories = new HashSet<Ipgmerchantcategory>(0);
    private Set<Ipgbatch> ipgbatchs = new HashSet<Ipgbatch>(0);
    private Set<Ipgsystemuser> ipgsystemusers = new HashSet<Ipgsystemuser>(0);
    private Set<Ipgmerchant> ipgmerchants = new HashSet<Ipgmerchant>(0);
    private Set<Ipgonusbinrange> ipgonusbinranges = new HashSet<Ipgonusbinrange>(0);
    private Set<Ipgsecuritylevel> ipgsecuritylevels = new HashSet<Ipgsecuritylevel>(0);
    private Set<Ipgriskprofile> ipgriskprofiles = new HashSet<Ipgriskprofile>(0);
    private Set<Ipgbin> ipgbinsForOnusstatus = new HashSet<Ipgbin>(0);
    private Set<Ipgbin> ipgbinsForStatus = new HashSet<Ipgbin>(0);
    private Set<Ipgtransaction> ipgtransactions = new HashSet<Ipgtransaction>(0);
    private Set<Ipgpasswordpolicy> ipgpasswordpolicies = new HashSet<Ipgpasswordpolicy>(0);
    private Set<Ipgsystemaudit> ipgsystemaudits = new HashSet<Ipgsystemaudit>(0);
    private Set<Ipgsection> ipgsections = new HashSet<Ipgsection>(0);
    private Set<Ipgpage> ipgpages = new HashSet<Ipgpage>(0);
    private Set<Ipguserroletype> ipguserroletypes = new HashSet<Ipguserroletype>(0);
    private Set<Ipguserrole> ipguserroles = new HashSet<Ipguserrole>(0);
    private Set<Ipgtask> ipgtasks = new HashSet<Ipgtask>(0);
    private Set<Ipgmerchant> ipgmerchantsForAuthenticationrequied = new HashSet<Ipgmerchant>(0);
    private Set<Epictxnrequests> epictxnrequestsesForStatus = new HashSet<Epictxnrequests>(0);
    private Set<Epictxnrequests> epictxnrequestsesForRequeststatus = new HashSet<Epictxnrequests>(0);
    private Set<Epictxnrequests> epictxnrequestsesForResponswstatus = new HashSet<Epictxnrequests>(0);
    private Set<Ipgsettlementfile> ipgsettlementfiles = new HashSet<Ipgsettlementfile>(0);

    public Ipgstatus() {
    }

    public Ipgstatus(String statuscode) {
        this.statuscode = statuscode;
    }

    public Ipgstatus(String statuscode, Set<Ipgmerchant> ipgmerchantsForAuthenticationrequied, Ipgstatuscategory ipgstatuscategory, String description, BigDecimal sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgheadmerchant> ipgheadmerchantsForStatuscode, Set<Ipgheadmerchant> ipgheadmerchantsForAuthenticationrequied, Set<Ipgheadmerchant> ipgheadmerchantsForTransactioninitaiatedstatus, Set<Ipgtransactionhistory> ipgtransactionhistories, Set<Ipgccbafile> ipgccbafiles, Set<Ipgmerchnatterminal> ipgmerchnatterminals, Set<Ipgmerchantcategory> ipgmerchantcategories, Set<Ipgbatch> ipgbatchs, Set<Ipgsystemuser> ipgsystemusers, Set<Ipgmerchant> ipgmerchants, Set<Ipgonusbinrange> ipgonusbinranges, Set<Ipgsecuritylevel> ipgsecuritylevels, Set<Ipgriskprofile> ipgriskprofiles, Set<Ipgbin> ipgbinsForOnusstatus, Set<Ipgbin> ipgbinsForStatus, Set<Ipgtransaction> ipgtransactions, Set<Ipgpasswordpolicy> ipgpasswordpolicies, Set<Ipgsystemaudit> ipgsystemaudits, Set<Ipgsection> ipgsections, Set<Ipgpage> ipgpages, Set<Ipguserroletype> ipguserroletypes, Set<Ipguserrole> ipguserroles, Set<Ipgtask> ipgtasks, Set<Epictxnrequests> epictxnrequestsesForRequeststatus, Set<Epictxnrequests> epictxnrequestsesForResponswstatus, Set<Epictxnrequests> epictxnrequestsesForStatus, Set<Ipgsettlementfile> ipgsettlementfiles) {
        this.statuscode = statuscode;
        this.ipgstatuscategory = ipgstatuscategory;
        this.description = description;
        this.sortkey = sortkey;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgheadmerchantsForStatuscode = ipgheadmerchantsForStatuscode;
        this.ipgheadmerchantsForAuthenticationrequied = ipgheadmerchantsForAuthenticationrequied;
        this.ipgheadmerchantsForTransactioninitaiatedstatus = ipgheadmerchantsForTransactioninitaiatedstatus;
        this.ipgtransactionhistories = ipgtransactionhistories;
        this.ipgccbafiles = ipgccbafiles;
        this.ipgmerchnatterminals = ipgmerchnatterminals;
        this.ipgmerchantcategories = ipgmerchantcategories;
        this.ipgbatchs = ipgbatchs;
        this.ipgsystemusers = ipgsystemusers;
        this.ipgmerchants = ipgmerchants;
        this.ipgonusbinranges = ipgonusbinranges;
        this.ipgsecuritylevels = ipgsecuritylevels;
        this.ipgriskprofiles = ipgriskprofiles;
        this.ipgbinsForOnusstatus = ipgbinsForOnusstatus;
        this.ipgbinsForStatus = ipgbinsForStatus;
        this.ipgtransactions = ipgtransactions;
        this.ipgpasswordpolicies = ipgpasswordpolicies;
        this.ipgsystemaudits = ipgsystemaudits;
        this.ipgsections = ipgsections;
        this.ipgpages = ipgpages;
        this.ipguserroletypes = ipguserroletypes;
        this.ipguserroles = ipguserroles;
        this.ipgtasks = ipgtasks;
        this.ipgmerchantsForAuthenticationrequied = ipgmerchantsForAuthenticationrequied;
        this.epictxnrequestsesForStatus = epictxnrequestsesForStatus;
        this.epictxnrequestsesForRequeststatus = epictxnrequestsesForRequeststatus;
        this.epictxnrequestsesForResponswstatus = epictxnrequestsesForResponswstatus;
        this.ipgsettlementfiles = ipgsettlementfiles;
    }

    @Id
    @Column(name = "STATUSCODE", unique = true, nullable = false, length = 16)
    public String getStatuscode() {
        return this.statuscode;
    }

    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUSCATEGORYCODE")
    public Ipgstatuscategory getIpgstatuscategory() {
        return this.ipgstatuscategory;
    }

    public void setIpgstatuscategory(Ipgstatuscategory ipgstatuscategory) {
        this.ipgstatuscategory = ipgstatuscategory;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "SORTKEY", precision = 22, scale = 0)
    public BigDecimal getSortkey() {
        return this.sortkey;
    }

    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByStatuscode")
    public Set<Ipgheadmerchant> getIpgheadmerchantsForStatuscode() {
        return this.ipgheadmerchantsForStatuscode;
    }

    public void setIpgheadmerchantsForStatuscode(Set<Ipgheadmerchant> ipgheadmerchantsForStatuscode) {
        this.ipgheadmerchantsForStatuscode = ipgheadmerchantsForStatuscode;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByAuthenticationrequied")
    public Set<Ipgheadmerchant> getIpgheadmerchantsForAuthenticationrequied() {
        return this.ipgheadmerchantsForAuthenticationrequied;
    }

    public void setIpgheadmerchantsForAuthenticationrequied(Set<Ipgheadmerchant> ipgheadmerchantsForAuthenticationrequied) {
        this.ipgheadmerchantsForAuthenticationrequied = ipgheadmerchantsForAuthenticationrequied;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByTransactioninitaiatedstatus")
    public Set<Ipgheadmerchant> getIpgheadmerchantsForTransactioninitaiatedstatus() {
        return this.ipgheadmerchantsForTransactioninitaiatedstatus;
    }

    public void setIpgheadmerchantsForTransactioninitaiatedstatus(Set<Ipgheadmerchant> ipgheadmerchantsForTransactioninitaiatedstatus) {
        this.ipgheadmerchantsForTransactioninitaiatedstatus = ipgheadmerchantsForTransactioninitaiatedstatus;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgtransactionhistory> getIpgtransactionhistories() {
        return this.ipgtransactionhistories;
    }

    public void setIpgtransactionhistories(Set<Ipgtransactionhistory> ipgtransactionhistories) {
        this.ipgtransactionhistories = ipgtransactionhistories;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgccbafile> getIpgccbafiles() {
        return this.ipgccbafiles;
    }

    public void setIpgccbafiles(Set<Ipgccbafile> ipgccbafiles) {
        this.ipgccbafiles = ipgccbafiles;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgmerchnatterminal> getIpgmerchnatterminals() {
        return this.ipgmerchnatterminals;
    }

    public void setIpgmerchnatterminals(Set<Ipgmerchnatterminal> ipgmerchnatterminals) {
        this.ipgmerchnatterminals = ipgmerchnatterminals;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgmerchantcategory> getIpgmerchantcategories() {
        return this.ipgmerchantcategories;
    }

    public void setIpgmerchantcategories(Set<Ipgmerchantcategory> ipgmerchantcategories) {
        this.ipgmerchantcategories = ipgmerchantcategories;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgbatch> getIpgbatchs() {
        return this.ipgbatchs;
    }

    public void setIpgbatchs(Set<Ipgbatch> ipgbatchs) {
        this.ipgbatchs = ipgbatchs;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgsystemuser> getIpgsystemusers() {
        return this.ipgsystemusers;
    }

    public void setIpgsystemusers(Set<Ipgsystemuser> ipgsystemusers) {
        this.ipgsystemusers = ipgsystemusers;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgmerchant> getIpgmerchants() {
        return this.ipgmerchants;
    }

    public void setIpgmerchants(Set<Ipgmerchant> ipgmerchants) {
        this.ipgmerchants = ipgmerchants;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgonusbinrange> getIpgonusbinranges() {
        return this.ipgonusbinranges;
    }

    public void setIpgonusbinranges(Set<Ipgonusbinrange> ipgonusbinranges) {
        this.ipgonusbinranges = ipgonusbinranges;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgsecuritylevel> getIpgsecuritylevels() {
        return this.ipgsecuritylevels;
    }

    public void setIpgsecuritylevels(Set<Ipgsecuritylevel> ipgsecuritylevels) {
        this.ipgsecuritylevels = ipgsecuritylevels;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgriskprofile> getIpgriskprofiles() {
        return this.ipgriskprofiles;
    }

    public void setIpgriskprofiles(Set<Ipgriskprofile> ipgriskprofiles) {
        this.ipgriskprofiles = ipgriskprofiles;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByOnusstatus")
    public Set<Ipgbin> getIpgbinsForOnusstatus() {
        return this.ipgbinsForOnusstatus;
    }

    public void setIpgbinsForOnusstatus(Set<Ipgbin> ipgbinsForOnusstatus) {
        this.ipgbinsForOnusstatus = ipgbinsForOnusstatus;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByStatus")
    public Set<Ipgbin> getIpgbinsForStatus() {
        return this.ipgbinsForStatus;
    }

    public void setIpgbinsForStatus(Set<Ipgbin> ipgbinsForStatus) {
        this.ipgbinsForStatus = ipgbinsForStatus;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgtransaction> getIpgtransactions() {
        return this.ipgtransactions;
    }

    public void setIpgtransactions(Set<Ipgtransaction> ipgtransactions) {
        this.ipgtransactions = ipgtransactions;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgpasswordpolicy> getIpgpasswordpolicies() {
        return this.ipgpasswordpolicies;
    }

    public void setIpgpasswordpolicies(Set<Ipgpasswordpolicy> ipgpasswordpolicies) {
        this.ipgpasswordpolicies = ipgpasswordpolicies;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgsystemaudit> getIpgsystemaudits() {
        return this.ipgsystemaudits;
    }

    public void setIpgsystemaudits(Set<Ipgsystemaudit> ipgsystemaudits) {
        this.ipgsystemaudits = ipgsystemaudits;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgsection> getIpgsections() {
        return this.ipgsections;
    }

    public void setIpgsections(Set<Ipgsection> ipgsections) {
        this.ipgsections = ipgsections;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgpage> getIpgpages() {
        return this.ipgpages;
    }

    public void setIpgpages(Set<Ipgpage> ipgpages) {
        this.ipgpages = ipgpages;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipguserroletype> getIpguserroletypes() {
        return this.ipguserroletypes;
    }

    public void setIpguserroletypes(Set<Ipguserroletype> ipguserroletypes) {
        this.ipguserroletypes = ipguserroletypes;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipguserrole> getIpguserroles() {
        return this.ipguserroles;
    }

    public void setIpguserroles(Set<Ipguserrole> ipguserroles) {
        this.ipguserroles = ipguserroles;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgtask> getIpgtasks() {
        return this.ipgtasks;
    }

    public void setIpgtasks(Set<Ipgtask> ipgtasks) {
        this.ipgtasks = ipgtasks;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByAuthenticationrequied")
    public Set<Ipgmerchant> getIpgmerchantsForAuthenticationrequied() {
        return this.ipgmerchantsForAuthenticationrequied;
    }

    public void setIpgmerchantsForAuthenticationrequied(Set<Ipgmerchant> ipgmerchantsForAuthenticationrequied) {
        this.ipgmerchantsForAuthenticationrequied = ipgmerchantsForAuthenticationrequied;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByStatus")
    public Set<Epictxnrequests> getEpictxnrequestsesForStatus() {
        return this.epictxnrequestsesForStatus;
    }

    public void setEpictxnrequestsesForStatus(Set<Epictxnrequests> epictxnrequestsesForStatus) {
        this.epictxnrequestsesForStatus = epictxnrequestsesForStatus;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByRequeststatus")
    public Set<Epictxnrequests> getEpictxnrequestsesForRequeststatus() {
        return this.epictxnrequestsesForRequeststatus;
    }

    public void setEpictxnrequestsesForRequeststatus(Set<Epictxnrequests> epictxnrequestsesForRequeststatus) {
        this.epictxnrequestsesForRequeststatus = epictxnrequestsesForRequeststatus;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgstatusByResponswstatus")
    public Set<Epictxnrequests> getEpictxnrequestsesForResponswstatus() {
        return this.epictxnrequestsesForResponswstatus;
    }

    public void setEpictxnrequestsesForResponswstatus(Set<Epictxnrequests> epictxnrequestsesForResponswstatus) {
        this.epictxnrequestsesForResponswstatus = epictxnrequestsesForResponswstatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ipgstatus")
    public Set<Ipgsettlementfile> getIpgsettlementfiles() {
        return this.ipgsettlementfiles;
    }

    public void setIpgsettlementfiles(Set<Ipgsettlementfile> ipgsettlementfiles) {
        this.ipgsettlementfiles = ipgsettlementfiles;
    }
}
