package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgsection generated by hbm2java
 */
@Entity
@Table(name = "IPGSECTION"
)
public class Ipgsection implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1299707164838558764L;
    private String sectioncode;
    private Ipgstatus ipgstatus;
    private String description;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgsectionpage> ipgsectionpages = new HashSet<Ipgsectionpage>(0);
    private Set<Ipguserrolesection> ipguserrolesections = new HashSet<Ipguserrolesection>(0);
    private Set<Ipgsystemaudit> ipgsystemaudits = new HashSet<Ipgsystemaudit>(0);
    private BigDecimal sortkey;

    public Ipgsection() {
    }

    public Ipgsection(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    public Ipgsection(String sectioncode, Ipgstatus ipgstatus, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgsectionpage> ipgsectionpages, Set<Ipguserrolesection> ipguserrolesections, Set<Ipgsystemaudit> ipgsystemaudits) {
        this.sectioncode = sectioncode;
        this.ipgstatus = ipgstatus;
        this.description = description;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgsectionpages = ipgsectionpages;
        this.ipguserrolesections = ipguserrolesections;
        this.ipgsystemaudits = ipgsystemaudits;
    }

    @Id

    @Column(name = "SECTIONCODE", unique = true, nullable = false, length = 16)
    public String getSectioncode() {
        return this.sectioncode;
    }

    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUSCODE")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    @Column(name = "DESCRIPTION", length = 64)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ipgsection")
    public Set<Ipgsectionpage> getIpgsectionpages() {
        return this.ipgsectionpages;
    }

    public void setIpgsectionpages(Set<Ipgsectionpage> ipgsectionpages) {
        this.ipgsectionpages = ipgsectionpages;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ipgsection")
    public Set<Ipguserrolesection> getIpguserrolesections() {
        return this.ipguserrolesections;
    }

    public void setIpguserrolesections(Set<Ipguserrolesection> ipguserrolesections) {
        this.ipguserrolesections = ipguserrolesections;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ipgsection")
    public Set<Ipgsystemaudit> getIpgsystemaudits() {
        return this.ipgsystemaudits;
    }

    public void setIpgsystemaudits(Set<Ipgsystemaudit> ipgsystemaudits) {
        this.ipgsystemaudits = ipgsystemaudits;
    }

    @Column(name = "SORTKEY", precision = 2, scale = 0)
    public BigDecimal getSortkey() {
        return sortkey;
    }

    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }

}
