package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgsecuritylevel generated by hbm2java
 */
@Entity
@Table(name="IPGSECURITYLEVEL"
    
)
public class Ipgsecuritylevel  implements java.io.Serializable {


     private String securitylevel;
     private Ipgstatus ipgstatus;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Ipgrule> ipgrules = new HashSet<Ipgrule>(0);

    public Ipgsecuritylevel() {
    }

	
    public Ipgsecuritylevel(String securitylevel) {
        this.securitylevel = securitylevel;
    }
    public Ipgsecuritylevel(String securitylevel, Ipgstatus ipgstatus, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgrule> ipgrules) {
       this.securitylevel = securitylevel;
       this.ipgstatus = ipgstatus;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.ipgrules = ipgrules;
    }
   
     @Id 
    
    @Column(name="SECURITYLEVEL", unique=true, nullable=false, length=16)
    public String getSecuritylevel() {
        return this.securitylevel;
    }
    
    public void setSecuritylevel(String securitylevel) {
        this.securitylevel = securitylevel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }
    
    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }
    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipgsecuritylevel")
    public Set<Ipgrule> getIpgrules() {
        return this.ipgrules;
    }
    
    public void setIpgrules(Set<Ipgrule> ipgrules) {
        this.ipgrules = ipgrules;
    }




}


