package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgstatuscategory generated by hbm2java
 */
@Entity
@Table(name="IPGSTATUSCATEGORY"
    
)
public class Ipgstatuscategory  implements java.io.Serializable {


     private String statuscategorycode;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Ipgstatus> ipgstatuses = new HashSet<Ipgstatus>(0);

    public Ipgstatuscategory() {
    }

	
    public Ipgstatuscategory(String statuscategorycode, String description) {
        this.statuscategorycode = statuscategorycode;
        this.description = description;
    }
    public Ipgstatuscategory(String statuscategorycode, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgstatus> ipgstatuses) {
       this.statuscategorycode = statuscategorycode;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.ipgstatuses = ipgstatuses;
    }
   
     @Id 
    
    @Column(name="STATUSCATEGORYCODE", unique=true, nullable=false, length=16)
    public String getStatuscategorycode() {
        return this.statuscategorycode;
    }
    
    public void setStatuscategorycode(String statuscategorycode) {
        this.statuscategorycode = statuscategorycode;
    }
    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipgstatuscategory")
    public Set<Ipgstatus> getIpgstatuses() {
        return this.ipgstatuses;
    }
    
    public void setIpgstatuses(Set<Ipgstatus> ipgstatuses) {
        this.ipgstatuses = ipgstatuses;
    }




}


