package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpgsectionpageId generated by hbm2java
 */
@Embeddable
public class IpgsectionpageId  implements java.io.Serializable {


     private String userrolecode;
     private String sectioncode;
     private String pagecode;

    public IpgsectionpageId() {
    }

    public IpgsectionpageId(String userrolecode, String sectioncode, String pagecode) {
       this.userrolecode = userrolecode;
       this.sectioncode = sectioncode;
       this.pagecode = pagecode;
    }
   

    @Column(name="USERROLECODE", nullable=false, length=16)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }

    @Column(name="SECTIONCODE", nullable=false, length=16)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="PAGECODE", nullable=false, length=16)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpgsectionpageId) ) return false;
		 IpgsectionpageId castOther = ( IpgsectionpageId ) other; 
         
		 return ( (this.getUserrolecode()==castOther.getUserrolecode()) || ( this.getUserrolecode()!=null && castOther.getUserrolecode()!=null && this.getUserrolecode().equals(castOther.getUserrolecode()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getPagecode()==castOther.getPagecode()) || ( this.getPagecode()!=null && castOther.getPagecode()!=null && this.getPagecode().equals(castOther.getPagecode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserrolecode() == null ? 0 : this.getUserrolecode().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getPagecode() == null ? 0 : this.getPagecode().hashCode() );
         return result;
   }   


}


