package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgservicecharge generated by hbm2java
 */
@Entity
@Table(name = "IPGSERVICECHARGE" )
public class Ipgservicecharge implements java.io.Serializable {

    private BigDecimal servicechargeid;
    private Ipgcurrency ipgcurrency;
    private Ipgservicechargetype ipgservicechargetype;
    private String description;
    private String value;
    private BigDecimal rate;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private Set<Ipgmerchantservicecharge> ipgmerchantservicecharges = new HashSet<Ipgmerchantservicecharge>(0);
    private Set<Ipgtransactioservicecharge> ipgtransactioservicecharges = new HashSet<Ipgtransactioservicecharge>(0);

    public Ipgservicecharge() {
    }

    public Ipgservicecharge(BigDecimal servicechargeid, Ipgservicechargetype ipgservicechargetype) {
        this.servicechargeid = servicechargeid;
        this.ipgservicechargetype = ipgservicechargetype;
    }

    public Ipgservicecharge(BigDecimal servicechargeid, Ipgcurrency ipgcurrency, Ipgservicechargetype ipgservicechargetype, Set<Ipgmerchantservicecharge> ipgmerchantservicecharges, String description, String value, BigDecimal rate, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgtransactioservicecharge> ipgtransactioservicecharges) {
        this.servicechargeid = servicechargeid;
        this.ipgcurrency = ipgcurrency;
        this.ipgservicechargetype = ipgservicechargetype;
        this.description = description;
        this.value = value;
        this.rate = rate;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.ipgmerchantservicecharges = ipgmerchantservicecharges;
        this.ipgtransactioservicecharges = ipgtransactioservicecharges;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGSERVICECHARGEID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name = "SERVICECHARGEID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getServicechargeid() {
        return this.servicechargeid;
    }

    public void setServicechargeid(BigDecimal servicechargeid) {
        this.servicechargeid = servicechargeid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CURRENCYCODE")
    public Ipgcurrency getIpgcurrency() {
        return this.ipgcurrency;
    }

    public void setIpgcurrency(Ipgcurrency ipgcurrency) {
        this.ipgcurrency = ipgcurrency;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SERVICECHARGETYPECODE", nullable = false)
    public Ipgservicechargetype getIpgservicechargetype() {
        return this.ipgservicechargetype;
    }

    public void setIpgservicechargetype(Ipgservicechargetype ipgservicechargetype) {
        this.ipgservicechargetype = ipgservicechargetype;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "VALUE")
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "RATE", precision = 22, scale = 0)
    public BigDecimal getRate() {
        return this.rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgservicecharge")
    public Set<Ipgtransactioservicecharge> getIpgtransactioservicecharges() {
        return this.ipgtransactioservicecharges;
    }

    public void setIpgtransactioservicecharges(Set<Ipgtransactioservicecharge> ipgtransactioservicecharges) {
        this.ipgtransactioservicecharges = ipgtransactioservicecharges;
    }

    @OneToMany(  fetch = FetchType.LAZY, mappedBy = "ipgservicecharge")
    public Set<Ipgmerchantservicecharge> getIpgmerchantservicecharges() {
        return this.ipgmerchantservicecharges;
    }

    public void setIpgmerchantservicecharges(Set<Ipgmerchantservicecharge> ipgmerchantservicecharges) {
        this.ipgmerchantservicecharges = ipgmerchantservicecharges;
    }
}
