package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgsystemaudit generated by hbm2java
 */
@Entity
@Table(name = "IPGSYSTEMAUDIT" )
public class Ipgsystemaudit implements java.io.Serializable {

    private BigDecimal systemauditid;
    private Ipgsection ipgsection;
    private Ipgpage ipgpage;
    private Ipguserrole ipguserrole;
    private Ipgstatus ipgstatus;
    private Ipgtask ipgtask;
    private String description;
    private String remarks;
    private String ip;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private String oldvalue;
    private String newvalue;

    public Ipgsystemaudit() {
    }

    public Ipgsystemaudit(BigDecimal systemauditid, Ipgsection ipgsection, Ipgpage ipgpage, Ipguserrole ipguserrole, Ipgtask ipgtask, String description) {
        this.systemauditid = systemauditid;
        this.ipgsection = ipgsection;
        this.ipgpage = ipgpage;
        this.ipguserrole = ipguserrole;
        this.ipgtask = ipgtask;
        this.description = description;
    }

    public Ipgsystemaudit(BigDecimal systemauditid, Ipgsection ipgsection, Ipgpage ipgpage, Ipguserrole ipguserrole, Ipgstatus ipgstatus, Ipgtask ipgtask, String description, String remarks, String ip, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
        this.systemauditid = systemauditid;
        this.ipgsection = ipgsection;
        this.ipgpage = ipgpage;
        this.ipguserrole = ipguserrole;
        this.ipgstatus = ipgstatus;
        this.ipgtask = ipgtask;
        this.description = description;
        this.remarks = remarks;
        this.ip = ip;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "IPGSYSTEMAUDITID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name = "SYSTEMAUDITID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getSystemauditid() {
        return this.systemauditid;
    }

    public void setSystemauditid(BigDecimal systemauditid) {
        this.systemauditid = systemauditid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SECTIONCODE", nullable = false)
    public Ipgsection getIpgsection() {
        return this.ipgsection;
    }

    public void setIpgsection(Ipgsection ipgsection) {
        this.ipgsection = ipgsection;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAGECODE", nullable = false)
    public Ipgpage getIpgpage() {
        return this.ipgpage;
    }

    public void setIpgpage(Ipgpage ipgpage) {
        this.ipgpage = ipgpage;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USERROLECODE", nullable = false)
    public Ipguserrole getIpguserrole() {
        return this.ipguserrole;
    }

    public void setIpguserrole(Ipguserrole ipguserrole) {
        this.ipguserrole = ipguserrole;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUSCODE")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }

    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TASKCODE", nullable = false)
    public Ipgtask getIpgtask() {
        return this.ipgtask;
    }

    public void setIpgtask(Ipgtask ipgtask) {
        this.ipgtask = ipgtask;
    }

    @Column(name = "DESCRIPTION", nullable = false)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "REMARKS")
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "IP", length = 64)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    } 
    
    @Column(name = "OLDVALUE")
    public String getOldvalue() {
        return oldvalue;
    }
    
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue;
    }
    
    @Column(name = "NEWVALUE")
    public String getNewvalue() {
        return newvalue;
    }
    
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue;
    }
    
}
