package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgtransactioservicecharge generated by hbm2java
 */
@Entity
@Table(name="IPGTRANSACTIOSERVICECHARGE"
    
)
public class Ipgtransactioservicecharge  implements java.io.Serializable {


     private String ipgtransactionid;
     private Ipgservicecharge ipgservicecharge;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgtransactioservicecharge() {
    }

	
    public Ipgtransactioservicecharge(String ipgtransactionid, Ipgservicecharge ipgservicecharge) {
        this.ipgtransactionid = ipgtransactionid;
        this.ipgservicecharge = ipgservicecharge;
    }
    public Ipgtransactioservicecharge(String ipgtransactionid, Ipgservicecharge ipgservicecharge, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.ipgtransactionid = ipgtransactionid;
       this.ipgservicecharge = ipgservicecharge;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 
    
    @Column(name="IPGTRANSACTIONID", unique=true, nullable=false, length=20)
    public String getIpgtransactionid() {
        return this.ipgtransactionid;
    }
    
    public void setIpgtransactionid(String ipgtransactionid) {
        this.ipgtransactionid = ipgtransactionid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SERVICECHARGECODE", nullable=false)
    public Ipgservicecharge getIpgservicecharge() {
        return this.ipgservicecharge;
    }
    
    public void setIpgservicecharge(Ipgservicecharge ipgservicecharge) {
        this.ipgservicecharge = ipgservicecharge;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


