package com.epic.epay.ipg.util.mapping;
// Generated Jul 24, 2018 9:52:25 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipgtriggersequence generated by hbm2java
 */
@Entity
@Table(name="IPGTRIGGERSEQUENCE")

public class Ipgtriggersequence  implements java.io.Serializable {


     private BigDecimal triggersequenceid;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public Ipgtriggersequence() {
    }

	
    public Ipgtriggersequence(BigDecimal triggersequenceid, String description) {
        this.triggersequenceid = triggersequenceid;
        this.description = description;
    }
    public Ipgtriggersequence(BigDecimal triggersequenceid, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.triggersequenceid = triggersequenceid;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 

    
    @Column(name="TRIGGERSEQUENCEID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getTriggersequenceid() {
        return this.triggersequenceid;
    }
    
    public void setTriggersequenceid(BigDecimal triggersequenceid) {
        this.triggersequenceid = triggersequenceid;
    }

    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}
