package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ipguserrole generated by hbm2java
 */
@Entity
@Table(name="IPGUSERROLE"
    
)
public class Ipguserrole  implements java.io.Serializable {


     private String userrolecode;
     private Ipguserroletype ipguserroletype;
     private Ipgstatus ipgstatus;
     private String description;
     private BigDecimal sortkey;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<Ipgsystemuser> ipgsystemusersForDualauthuserrole = new HashSet<Ipgsystemuser>(0);
     private Set<Ipgsectionpage> ipgsectionpages = new HashSet<Ipgsectionpage>(0);
     private Set<Ipgsystemuser> ipgsystemusersForUserrolecode = new HashSet<Ipgsystemuser>(0);
     private Set<Ipgsystemaudit> ipgsystemaudits = new HashSet<Ipgsystemaudit>(0);

    public Ipguserrole() {
    }

	
    public Ipguserrole(String userrolecode) {
        this.userrolecode = userrolecode;
    }
    public Ipguserrole(String userrolecode, Ipguserroletype ipguserroletype, Ipgstatus ipgstatus, String description, BigDecimal sortkey, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<Ipgsystemuser> ipgsystemusersForDualauthuserrole, Set<Ipgsectionpage> ipgsectionpages, Set<Ipgsystemuser> ipgsystemusersForUserrolecode, Set<Ipgsystemaudit> ipgsystemaudits) {
       this.userrolecode = userrolecode;
       this.ipguserroletype = ipguserroletype;
       this.ipgstatus = ipgstatus;
       this.description = description;
       this.sortkey = sortkey;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.ipgsystemusersForDualauthuserrole = ipgsystemusersForDualauthuserrole;
       this.ipgsectionpages = ipgsectionpages;
       this.ipgsystemusersForUserrolecode = ipgsystemusersForUserrolecode;
       this.ipgsystemaudits = ipgsystemaudits;
    }
   
     @Id 
    
    @Column(name="USERROLECODE", unique=true, nullable=false, length=16)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLETYPECODE")
    public Ipguserroletype getIpguserroletype() {
        return this.ipguserroletype;
    }
    
    public void setIpguserroletype(Ipguserroletype ipguserroletype) {
        this.ipguserroletype = ipguserroletype;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUSCODE")
    public Ipgstatus getIpgstatus() {
        return this.ipgstatus;
    }
    
    public void setIpgstatus(Ipgstatus ipgstatus) {
        this.ipgstatus = ipgstatus;
    }
    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SORTKEY", precision=22, scale=0)
    public BigDecimal getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(BigDecimal sortkey) {
        this.sortkey = sortkey;
    }
    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=7)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipguserroleByDualauthuserrole")
    public Set<Ipgsystemuser> getIpgsystemusersForDualauthuserrole() {
        return this.ipgsystemusersForDualauthuserrole;
    }
    
    public void setIpgsystemusersForDualauthuserrole(Set<Ipgsystemuser> ipgsystemusersForDualauthuserrole) {
        this.ipgsystemusersForDualauthuserrole = ipgsystemusersForDualauthuserrole;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipguserrole")
    public Set<Ipgsectionpage> getIpgsectionpages() {
        return this.ipgsectionpages;
    }
    
    public void setIpgsectionpages(Set<Ipgsectionpage> ipgsectionpages) {
        this.ipgsectionpages = ipgsectionpages;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipguserroleByUserrolecode")
    public Set<Ipgsystemuser> getIpgsystemusersForUserrolecode() {
        return this.ipgsystemusersForUserrolecode;
    }
    
    public void setIpgsystemusersForUserrolecode(Set<Ipgsystemuser> ipgsystemusersForUserrolecode) {
        this.ipgsystemusersForUserrolecode = ipgsystemusersForUserrolecode;
    }
@OneToMany(  fetch=FetchType.LAZY, mappedBy="ipguserrole")
    public Set<Ipgsystemaudit> getIpgsystemaudits() {
        return this.ipgsystemaudits;
    }
    
    public void setIpgsystemaudits(Set<Ipgsystemaudit> ipgsystemaudits) {
        this.ipgsystemaudits = ipgsystemaudits;
    }




}


