package com.epic.epay.ipg.util.mapping;
// Generated Oct 24, 2013 11:34:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpguserrolesectionId generated by hbm2java
 */
@Embeddable
public class IpguserrolesectionId  implements java.io.Serializable {


     private String userrolecode;
     private String sectioncode;

    public IpguserrolesectionId() {
    }

    public IpguserrolesectionId(String userrolecode, String sectioncode) {
       this.userrolecode = userrolecode;
       this.sectioncode = sectioncode;
    }
   

    @Column(name="USERROLECODE", nullable=false, length=16)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }

    @Column(name="SECTIONCODE", nullable=false, length=16)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IpguserrolesectionId) ) return false;
		 IpguserrolesectionId castOther = ( IpguserrolesectionId ) other; 
         
		 return ( (this.getUserrolecode()==castOther.getUserrolecode()) || ( this.getUserrolecode()!=null && castOther.getUserrolecode()!=null && this.getUserrolecode().equals(castOther.getUserrolecode()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserrolecode() == null ? 0 : this.getUserrolecode().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         return result;
   }   


}


